using System.Collections.Generic;
using System.Linq;

namespace SimConnectNet.Mapping
{
    public static partial class MappingUtils
    {
        public static string ConvertSimVariableToSimulationString(SimVariable variable)
        {
            if(SimVariableMappings.TryGetValue(variable, out var mapping))
            {
                return mapping;
            }

            return null;
        }

        public static bool TryConvertSimulationStringToSimVariable(string simString, out SimVariable variable)
        {
            var kvps = SimVariableMappings.Where(uom => uom.Value == simString)
                .ToList();

            if (kvps.Any())
            {
                variable = kvps.FirstOrDefault().Key;
                return true;
            }

            variable = SimVariable.None;
            return false;
        }

        private static readonly Dictionary<SimVariable, string> SimVariableMappings = new Dictionary<SimVariable, string>
        {
            { SimVariable.None, "NONE" },
            { SimVariable.AngleOfAttackIndicator, "ANGLE OF ATTACK INDICATOR" },
            { SimVariable.GunAmmo, "GUN AMMO" },
            { SimVariable.CannonAmmo, "CANNON AMMO" },
            { SimVariable.RocketAmmo, "ROCKET AMMO" },
            { SimVariable.BombAmmo, "BOMB AMMO" },
            { SimVariable.LightOnStates, "LIGHT ON STATES" },
            { SimVariable.LightStates, "LIGHT STATES" },
            { SimVariable.LightPanel, "LIGHT PANEL" },
            { SimVariable.LightStrobe, "LIGHT STROBE" },
            { SimVariable.LightLanding, "LIGHT LANDING" },
            { SimVariable.StrobeFlash, "STROBE FLASH" },
            { SimVariable.LightTaxi, "LIGHT TAXI" },
            { SimVariable.LightBeacon, "LIGHT BEACON" },
            { SimVariable.LightNav, "LIGHT NAV" },
            { SimVariable.LightLogo, "LIGHT LOGO" },
            { SimVariable.LightWing, "LIGHT WING" },
            { SimVariable.LightRecognition, "LIGHT RECOGNITION" },
            { SimVariable.LightCabin, "LIGHT CABIN" },
            { SimVariable.LandingLightPbh, "LANDING LIGHT PBH" },
            { SimVariable.LightNavOn, "LIGHT NAV ON" },
            { SimVariable.LightBeaconOn, "LIGHT BEACON ON" },
            { SimVariable.LightLandingOn, "LIGHT LANDING ON" },
            { SimVariable.LightTaxiOn, "LIGHT TAXI ON" },
            { SimVariable.LightStrobeOn, "LIGHT STROBE ON" },
            { SimVariable.LightPanelOn, "LIGHT PANEL ON" },
            { SimVariable.LightRecognitionOn, "LIGHT RECOGNITION ON" },
            { SimVariable.LightWingOn, "LIGHT WING ON" },
            { SimVariable.LightLogoOn, "LIGHT LOGO ON" },
            { SimVariable.LightCabinOn, "LIGHT CABIN ON" },
            { SimVariable.LightHeadOn, "LIGHT HEAD ON" },
            { SimVariable.LightBrakeOn, "LIGHT BRAKE ON" },
            { SimVariable.WheelRpm, "WHEEL RPM" },
            { SimVariable.CenterWheelRpm, "CENTER WHEEL RPM" },
            { SimVariable.LeftWheelRpm, "LEFT WHEEL RPM" },
            { SimVariable.RightWheelRpm, "RIGHT WHEEL RPM" },
            { SimVariable.AuxWheelRpm, "AUX WHEEL RPM" },
            { SimVariable.WheelRotationAngle, "WHEEL ROTATION ANGLE" },
            { SimVariable.CenterWheelRotationAngle, "CENTER WHEEL ROTATION ANGLE" },
            { SimVariable.LeftWheelRotationAngle, "LEFT WHEEL ROTATION ANGLE" },
            { SimVariable.RightWheelRotationAngle, "RIGHT WHEEL ROTATION ANGLE" },
            { SimVariable.AuxWheelRotationAngle, "AUX WHEEL ROTATION ANGLE" },
            { SimVariable.SigmaSqrt, "SIGMA SQRT" },
            { SimVariable.DynamicPressure, "DYNAMIC PRESSURE" },
            { SimVariable.TotalVelocity, "TOTAL VELOCITY" },
            { SimVariable.TotalWorldVelocity, "TOTAL WORLD VELOCITY" },
            { SimVariable.GroundVelocity, "GROUND VELOCITY" },
            { SimVariable.SurfaceRelativeGroundSpeed, "SURFACE RELATIVE GROUND SPEED" },
            { SimVariable.AirspeedTrue, "AIRSPEED TRUE" },
            { SimVariable.AirspeedIndicated, "AIRSPEED INDICATED" },
            { SimVariable.AirspeedSelectIndicatedOrTrue, "AIRSPEED SELECT INDICATED OR TRUE" },
            { SimVariable.AirspeedTrueCalibrate, "AIRSPEED TRUE CALIBRATE" },
            { SimVariable.AirspeedBarberPole, "AIRSPEED BARBER POLE" },
            { SimVariable.AirspeedMach, "AIRSPEED MACH" },
            { SimVariable.VerticalSpeed, "VERTICAL SPEED" },
            { SimVariable.VariometerRate, "VARIOMETER RATE" },
            { SimVariable.VariometerSwitch, "VARIOMETER SWITCH" },
            { SimVariable.MachMaxOperate, "MACH MAX OPERATE" },
            { SimVariable.StallWarning, "STALL WARNING" },
            { SimVariable.OverspeedWarning, "OVERSPEED WARNING" },
            { SimVariable.BarberPoleMach, "BARBER POLE MACH" },
            { SimVariable.VelocityBodyX, "VELOCITY BODY X" },
            { SimVariable.VelocityBodyY, "VELOCITY BODY Y" },
            { SimVariable.VelocityBodyZ, "VELOCITY BODY Z" },
            { SimVariable.VelocityWorldX, "VELOCITY WORLD X" },
            { SimVariable.VelocityWorldY, "VELOCITY WORLD Y" },
            { SimVariable.VelocityWorldZ, "VELOCITY WORLD Z" },
            { SimVariable.RelativeWindVelocityBodyX, "RELATIVE WIND VELOCITY BODY X" },
            { SimVariable.RelativeWindVelocityBodyY, "RELATIVE WIND VELOCITY BODY Y" },
            { SimVariable.RelativeWindVelocityBodyZ, "RELATIVE WIND VELOCITY BODY Z" },
            { SimVariable.AccelerationWorldX, "ACCELERATION WORLD X" },
            { SimVariable.AccelerationWorldY, "ACCELERATION WORLD Y" },
            { SimVariable.AccelerationWorldZ, "ACCELERATION WORLD Z" },
            { SimVariable.AccelerationBodyX, "ACCELERATION BODY X" },
            { SimVariable.AccelerationBodyY, "ACCELERATION BODY Y" },
            { SimVariable.AccelerationBodyZ, "ACCELERATION BODY Z" },
            { SimVariable.RotationVelocityBodyX, "ROTATION VELOCITY BODY X" },
            { SimVariable.RotationVelocityBodyY, "ROTATION VELOCITY BODY Y" },
            { SimVariable.RotationVelocityBodyZ, "ROTATION VELOCITY BODY Z" },
            { SimVariable.DesignSpeedVs0, "DESIGN SPEED VS0" },
            { SimVariable.DesignSpeedVs1, "DESIGN SPEED VS1" },
            { SimVariable.DesignSpeedVc, "DESIGN SPEED VC" },
            { SimVariable.DesignSpeedMinRotation, "DESIGN SPEED MIN ROTATION" },
            { SimVariable.DesignSpeedClimb, "DESIGN SPEED CLIMB" },
            { SimVariable.DesignCruiseAlt, "DESIGN CRUISE ALT" },
            { SimVariable.DesignTakeoffSpeed, "DESIGN TAKEOFF SPEED" },
            { SimVariable.AiControls, "AI CONTROLS" },
            { SimVariable.DelegateControlsToAi, "DELEGATE CONTROLS TO AI" },
            { SimVariable.MinDragVelocity, "MIN DRAG VELOCITY" },
            { SimVariable.PlaneLatitude, "PLANE LATITUDE" },
            { SimVariable.PlaneLongitude, "PLANE LONGITUDE" },
            { SimVariable.PlaneAltitude, "PLANE ALTITUDE" },
            { SimVariable.PlaneAltAboveGround, "PLANE ALT ABOVE GROUND" },
            { SimVariable.PlanePitchDegrees, "PLANE PITCH DEGREES" },
            { SimVariable.PlaneBankDegrees, "PLANE BANK DEGREES" },
            { SimVariable.PlaneHeadingDegreesMagnetic, "PLANE HEADING DEGREES MAGNETIC" },
            { SimVariable.PlaneHeadingDegreesTrue, "PLANE HEADING DEGREES TRUE" },
            { SimVariable.IndicatedAltitude, "INDICATED ALTITUDE" },
            { SimVariable.PressureAltitude, "PRESSURE ALTITUDE" },
            { SimVariable.KohlsmanSettingMb, "KOHLSMAN SETTING MB" },
            { SimVariable.KohlsmanSettingHg, "KOHLSMAN SETTING HG" },
            { SimVariable.AttitudeIndicatorPitchDegrees, "ATTITUDE INDICATOR PITCH DEGREES" },
            { SimVariable.AttitudeIndicatorBankDegrees, "ATTITUDE INDICATOR BANK DEGREES" },
            { SimVariable.AttitudeBarsPosition, "ATTITUDE BARS POSITION" },
            { SimVariable.AttitudeCage, "ATTITUDE CAGE" },
            { SimVariable.Magvar, "MAGVAR" },
            { SimVariable.WiskeyCompassIndicationDegrees, "WISKEY COMPASS INDICATION DEGREES" },
            { SimVariable.MagneticCompass, "MAGNETIC COMPASS" },
            { SimVariable.PlaneHeadingDegreesGyro, "PLANE HEADING DEGREES GYRO" },
            { SimVariable.GyroDriftError, "GYRO DRIFT ERROR" },
            { SimVariable.DeltaHeadingRate, "DELTA HEADING RATE" },
            { SimVariable.TurnIndicatorRate, "TURN INDICATOR RATE" },
            { SimVariable.TurnIndicatorSwitch, "TURN INDICATOR SWITCH" },
            { SimVariable.GroundAltitude, "GROUND ALTITUDE" },
            { SimVariable.SimOnGround, "SIM ON GROUND" },
            { SimVariable.SimShouldSetOnGround, "SIM SHOULD SET ON GROUND" },
            { SimVariable.TurnCoordinatorBall, "TURN COORDINATOR BALL" },
            { SimVariable.YokeYPosition, "YOKE Y POSITION" },
            { SimVariable.YokeYIndicator, "YOKE Y INDICATOR" },
            { SimVariable.YokeXPosition, "YOKE X POSITION" },
            { SimVariable.YokeXInidicator, "YOKE X INIDICATOR" },
            { SimVariable.YokeXIndicator, "YOKE X INDICATOR" },
            { SimVariable.AileronPosition, "AILERON POSITION" },
            { SimVariable.RudderPedalPosition, "RUDDER PEDAL POSITION" },
            { SimVariable.RudderPedalIndicator, "RUDDER PEDAL INDICATOR" },
            { SimVariable.RudderPosition, "RUDDER POSITION" },
            { SimVariable.ElevatorPosition, "ELEVATOR POSITION" },
            { SimVariable.ElevatorTrimPosition, "ELEVATOR TRIM POSITION" },
            { SimVariable.ElevatorTrimIndicator, "ELEVATOR TRIM INDICATOR" },
            { SimVariable.ElevatorTrimPct, "ELEVATOR TRIM PCT" },
            { SimVariable.BrakeLeftPosition, "BRAKE LEFT POSITION" },
            { SimVariable.BrakeRightPosition, "BRAKE RIGHT POSITION" },
            { SimVariable.BrakeIndicator, "BRAKE INDICATOR" },
            { SimVariable.BrakeParkingPosition, "BRAKE PARKING POSITION" },
            { SimVariable.BrakeParkingIndicator, "BRAKE PARKING INDICATOR" },
            { SimVariable.BrakeDependentHydraulicPressure, "BRAKE DEPENDENT HYDRAULIC PRESSURE" },
            { SimVariable.SpoilersArmed, "SPOILERS ARMED" },
            { SimVariable.SpoilersHandlePosition, "SPOILERS HANDLE POSITION" },
            { SimVariable.SpoilersLeftPosition, "SPOILERS LEFT POSITION" },
            { SimVariable.SpoilersRightPosition, "SPOILERS RIGHT POSITION" },
            { SimVariable.FlyByWireElacSwitch, "FLY BY WIRE ELAC SWITCH" },
            { SimVariable.FlyByWireFacSwitch, "FLY BY WIRE FAC SWITCH" },
            { SimVariable.FlyByWireSecSwitch, "FLY BY WIRE SEC SWITCH" },
            { SimVariable.FlyByWireElacFailed, "FLY BY WIRE ELAC FAILED" },
            { SimVariable.FlyByWireFacFailed, "FLY BY WIRE FAC FAILED" },
            { SimVariable.FlyByWireSecFailed, "FLY BY WIRE SEC FAILED" },
            { SimVariable.FlyByWireAlphaProtection, "FLY BY WIRE ALPHA PROTECTION" },
            { SimVariable.FlapsNumHandlePositions, "FLAPS NUM HANDLE POSITIONS" },
            { SimVariable.FlapsHandlePercent, "FLAPS HANDLE PERCENT" },
            { SimVariable.FlapsHandleIndex, "FLAPS HANDLE INDEX" },
            { SimVariable.TrailingEdgeFlapsLeftPercent, "TRAILING EDGE FLAPS LEFT PERCENT" },
            { SimVariable.TrailingEdgeFlapsRightPercent, "TRAILING EDGE FLAPS RIGHT PERCENT" },
            { SimVariable.LeadingEdgeFlapsLeftPercent, "LEADING EDGE FLAPS LEFT PERCENT" },
            { SimVariable.LeadingEdgeFlapsRightPercent, "LEADING EDGE FLAPS RIGHT PERCENT" },
            { SimVariable.TrailingEdgeFlapsLeftAngle, "TRAILING EDGE FLAPS LEFT ANGLE" },
            { SimVariable.TrailingEdgeFlapsRightAngle, "TRAILING EDGE FLAPS RIGHT ANGLE" },
            { SimVariable.LeadingEdgeFlapsLeftAngle, "LEADING EDGE FLAPS LEFT ANGLE" },
            { SimVariable.LeadingEdgeFlapsRightAngle, "LEADING EDGE FLAPS RIGHT ANGLE" },
            { SimVariable.FlapPositionSet, "FLAP POSITION SET" },
            { SimVariable.IsGearRetractable, "IS GEAR RETRACTABLE" },
            { SimVariable.IsGearWheels, "IS GEAR WHEELS" },
            { SimVariable.IsGearSkis, "IS GEAR SKIS" },
            { SimVariable.IsGearFloats, "IS GEAR FLOATS" },
            { SimVariable.IsGearSkids, "IS GEAR SKIDS" },
            { SimVariable.GearHandlePosition, "GEAR HANDLE POSITION" },
            { SimVariable.GearEmergencyHandlePosition, "GEAR EMERGENCY HANDLE POSITION" },
            { SimVariable.GearCenterPosition, "GEAR CENTER POSITION" },
            { SimVariable.GearLeftPosition, "GEAR LEFT POSITION" },
            { SimVariable.GearRightPosition, "GEAR RIGHT POSITION" },
            { SimVariable.GearTailPosition, "GEAR TAIL POSITION" },
            { SimVariable.GearAuxPosition, "GEAR AUX POSITION" },
            { SimVariable.GearPosition, "GEAR POSITION" },
            { SimVariable.GearAnimationPosition, "GEAR ANIMATION POSITION" },
            { SimVariable.GearTotalPctExtended, "GEAR TOTAL PCT EXTENDED" },
            { SimVariable.GearWarning, "GEAR WARNING" },
            { SimVariable.TailwheelLockOn, "TAILWHEEL LOCK ON" },
            { SimVariable.NosewheelLockOn, "NOSEWHEEL LOCK ON" },
            { SimVariable.CowlFlaps, "COWL FLAPS" },
            { SimVariable.AvionicsMasterSwitch, "AVIONICS MASTER SWITCH" },
            { SimVariable.PanelAutoFeatherSwitch, "PANEL AUTO FEATHER SWITCH" },
            { SimVariable.PanelAntiIceSwitch, "PANEL ANTI ICE SWITCH" },
            { SimVariable.AutoBrakeSwitchCb, "AUTO BRAKE SWITCH CB" },
            { SimVariable.AntiskidBrakesActive, "ANTISKID BRAKES ACTIVE" },
            { SimVariable.WaterRudderHandlePosition, "WATER RUDDER HANDLE POSITION" },
            { SimVariable.WaterLeftRudderExtended, "WATER LEFT RUDDER EXTENDED" },
            { SimVariable.WaterRightRudderExtended, "WATER RIGHT RUDDER EXTENDED" },
            { SimVariable.RetractFloatSwitch, "RETRACT FLOAT SWITCH" },
            { SimVariable.RetractLeftFloatExtended, "RETRACT LEFT FLOAT EXTENDED" },
            { SimVariable.RetractRightFloatExtended, "RETRACT RIGHT FLOAT EXTENDED" },
            { SimVariable.GearCenterSteerAngle, "GEAR CENTER STEER ANGLE" },
            { SimVariable.GearLeftSteerAngle, "GEAR LEFT STEER ANGLE" },
            { SimVariable.GearRightSteerAngle, "GEAR RIGHT STEER ANGLE" },
            { SimVariable.GearAuxSteerAngle, "GEAR AUX STEER ANGLE" },
            { SimVariable.GearSteerAngle, "GEAR STEER ANGLE" },
            { SimVariable.WaterLeftRudderSteerAngle, "WATER LEFT RUDDER STEER ANGLE" },
            { SimVariable.WaterRightRudderSteerAngle, "WATER RIGHT RUDDER STEER ANGLE" },
            { SimVariable.GearCenterSteerAnglePct, "GEAR CENTER STEER ANGLE PCT" },
            { SimVariable.GearLeftSteerAnglePct, "GEAR LEFT STEER ANGLE PCT" },
            { SimVariable.GearRightSteerAnglePct, "GEAR RIGHT STEER ANGLE PCT" },
            { SimVariable.GearAuxSteerAnglePct, "GEAR AUX STEER ANGLE PCT" },
            { SimVariable.GearSteerAnglePct, "GEAR STEER ANGLE PCT" },
            { SimVariable.WaterLeftRudderSteerAnglePct, "WATER LEFT RUDDER STEER ANGLE PCT" },
            { SimVariable.WaterRightRudderSteerAnglePct, "WATER RIGHT RUDDER STEER ANGLE PCT" },
            { SimVariable.SteerInputControl, "STEER INPUT CONTROL" },
            { SimVariable.ElevatorDeflection, "ELEVATOR DEFLECTION" },
            { SimVariable.ElevatorDeflectionPct, "ELEVATOR DEFLECTION PCT" },
            { SimVariable.AileronLeftDeflection, "AILERON LEFT DEFLECTION" },
            { SimVariable.AileronLeftDeflectionPct, "AILERON LEFT DEFLECTION PCT" },
            { SimVariable.AileronRightDeflection, "AILERON RIGHT DEFLECTION" },
            { SimVariable.AileronRightDeflectionPct, "AILERON RIGHT DEFLECTION PCT" },
            { SimVariable.AileronAverageDeflection, "AILERON AVERAGE DEFLECTION" },
            { SimVariable.AileronTrim, "AILERON TRIM" },
            { SimVariable.AileronTrimPct, "AILERON TRIM PCT" },
            { SimVariable.RudderDeflection, "RUDDER DEFLECTION" },
            { SimVariable.RudderDeflectionPct, "RUDDER DEFLECTION PCT" },
            { SimVariable.RudderTrim, "RUDDER TRIM" },
            { SimVariable.RudderTrimPct, "RUDDER TRIM PCT" },
            { SimVariable.WingFlexPct, "WING FLEX PCT" },
            { SimVariable.WingArea, "WING AREA" },
            { SimVariable.WingSpan, "WING SPAN" },
            { SimVariable.PropSyncActive, "PROP SYNC ACTIVE" },
            { SimVariable.IncidenceAlpha, "INCIDENCE ALPHA" },
            { SimVariable.IncidenceBeta, "INCIDENCE BETA" },
            { SimVariable.BetaDot, "BETA DOT" },
            { SimVariable.LinearClAlpha, "LINEAR CL ALPHA" },
            { SimVariable.StallAlpha, "STALL ALPHA" },
            { SimVariable.ZeroLiftAlpha, "ZERO LIFT ALPHA" },
            { SimVariable.CgPercent, "CG PERCENT" },
            { SimVariable.CgPercentLateral, "CG PERCENT LATERAL" },
            { SimVariable.CgAftLimit, "CG AFT LIMIT" },
            { SimVariable.CgFwdLimit, "CG FWD LIMIT" },
            { SimVariable.CgMaxMach, "CG MAX MACH" },
            { SimVariable.CgMinMach, "CG MIN MACH" },
            { SimVariable.PayloadStationWeight, "PAYLOAD STATION WEIGHT" },
            { SimVariable.PayloadStationName, "PAYLOAD STATION NAME" },
            { SimVariable.PayloadStationCount, "PAYLOAD STATION COUNT" },
            { SimVariable.PayloadStationObject, "PAYLOAD STATION OBJECT" },
            { SimVariable.PayloadStationNumSimobjects, "PAYLOAD STATION NUM SIMOBJECTS" },
            { SimVariable.ElevonDeflection, "ELEVON DEFLECTION" },
            { SimVariable.FoldingWingLeftPercent, "FOLDING WING LEFT PERCENT" },
            { SimVariable.FoldingWingRightPercent, "FOLDING WING RIGHT PERCENT" },
            { SimVariable.FoldingWingHandlePosition, "FOLDING WING HANDLE POSITION" },
            { SimVariable.CanopyOpen, "CANOPY OPEN" },
            { SimVariable.TailhookPosition, "TAILHOOK POSITION" },
            { SimVariable.TailhookHandle, "TAILHOOK HANDLE" },
            { SimVariable.LaunchbarPosition, "LAUNCHBAR POSITION" },
            { SimVariable.LaunchbarSwitch, "LAUNCHBAR SWITCH" },
            { SimVariable.LaunchbarHeldExtended, "LAUNCHBAR HELD EXTENDED" },
            { SimVariable.ExitOpen, "EXIT OPEN" },
            { SimVariable.ExitType, "EXIT TYPE" },
            { SimVariable.ExitPosx, "EXIT POSX" },
            { SimVariable.ExitPosy, "EXIT POSY" },
            { SimVariable.ExitPosz, "EXIT POSZ" },
            { SimVariable.RadioHeight, "RADIO HEIGHT" },
            { SimVariable.DecisionHeight, "DECISION HEIGHT" },
            { SimVariable.DecisionAltitudeMsl, "DECISION ALTITUDE MSL" },
            { SimVariable.TotalWeight, "TOTAL WEIGHT" },
            { SimVariable.MaxGrossWeight, "MAX GROSS WEIGHT" },
            { SimVariable.EmptyWeight, "EMPTY WEIGHT" },
            { SimVariable.EmptyWeightPitchMoi, "EMPTY WEIGHT PITCH MOI" },
            { SimVariable.EmptyWeightRollMoi, "EMPTY WEIGHT ROLL MOI" },
            { SimVariable.EmptyWeightYawMoi, "EMPTY WEIGHT YAW MOI" },
            { SimVariable.EmptyWeightCrossCoupledMoi, "EMPTY WEIGHT CROSS COUPLED MOI" },
            { SimVariable.TotalWeightPitchMoi, "TOTAL WEIGHT PITCH MOI" },
            { SimVariable.TotalWeightRollMoi, "TOTAL WEIGHT ROLL MOI" },
            { SimVariable.TotalWeightYawMoi, "TOTAL WEIGHT YAW MOI" },
            { SimVariable.TotalWeightCrossCoupledMoi, "TOTAL WEIGHT CROSS COUPLED MOI" },
            { SimVariable.WaterBallastValve, "WATER BALLAST VALVE" },
            { SimVariable.AutopilotMaster, "AUTOPILOT MASTER" },
            { SimVariable.AutopilotWingLeveler, "AUTOPILOT WING LEVELER" },
            { SimVariable.AutopilotNav1Lock, "AUTOPILOT NAV1 LOCK" },
            { SimVariable.AutopilotHeadingLock, "AUTOPILOT HEADING LOCK" },
            { SimVariable.AutopilotHeadingLockDir, "AUTOPILOT HEADING LOCK DIR" },
            { SimVariable.AutopilotAltitudeLock, "AUTOPILOT ALTITUDE LOCK" },
            { SimVariable.AutopilotAltitudeLockVar, "AUTOPILOT ALTITUDE LOCK VAR" },
            { SimVariable.AutopilotAttitudeHold, "AUTOPILOT ATTITUDE HOLD" },
            { SimVariable.AutopilotGlideslopeHold, "AUTOPILOT GLIDESLOPE HOLD" },
            { SimVariable.AutopilotApproachHold, "AUTOPILOT APPROACH HOLD" },
            { SimVariable.AutopilotBackcourseHold, "AUTOPILOT BACKCOURSE HOLD" },
            { SimVariable.AutopilotYawDamper, "AUTOPILOT YAW DAMPER" },
            { SimVariable.AutopilotAirspeedHold, "AUTOPILOT AIRSPEED HOLD" },
            { SimVariable.AutopilotAirspeedHoldVar, "AUTOPILOT AIRSPEED HOLD VAR" },
            { SimVariable.AutopilotMachHold, "AUTOPILOT MACH HOLD" },
            { SimVariable.AutopilotMachHoldVar, "AUTOPILOT MACH HOLD VAR" },
            { SimVariable.AutopilotVerticalHold, "AUTOPILOT VERTICAL HOLD" },
            { SimVariable.AutopilotVerticalHoldVar, "AUTOPILOT VERTICAL HOLD VAR" },
            { SimVariable.AutopilotAltitudeManuallyTunable, "AUTOPILOT ALTITUDE MANUALLY TUNABLE" },
            { SimVariable.AutopilotHeadingManuallyTunable, "AUTOPILOT HEADING MANUALLY TUNABLE" },
            { SimVariable.AutopilotThrottleArm, "AUTOPILOT THROTTLE ARM" },
            { SimVariable.AutopilotTakeoffPowerActive, "AUTOPILOT TAKEOFF POWER ACTIVE" },
            { SimVariable.AutopilotRpmHold, "AUTOPILOT RPM HOLD" },
            { SimVariable.AutopilotRpmHoldVar, "AUTOPILOT RPM HOLD VAR" },
            { SimVariable.AutopilotSpeedSetting, "AUTOPILOT SPEED SETTING" },
            { SimVariable.AutopilotAirspeedAcquisition, "AUTOPILOT AIRSPEED ACQUISITION" },
            { SimVariable.AutopilotAirspeedHoldCurrent, "AUTOPILOT AIRSPEED HOLD CURRENT" },
            { SimVariable.AutopilotMaxSpeedHold, "AUTOPILOT MAX SPEED HOLD" },
            { SimVariable.AutopilotCruiseSpeedHold, "AUTOPILOT CRUISE SPEED HOLD" },
            { SimVariable.AutopilotFlightDirectorActive, "AUTOPILOT FLIGHT DIRECTOR ACTIVE" },
            { SimVariable.AutopilotFlightDirectorPitch, "AUTOPILOT FLIGHT DIRECTOR PITCH" },
            { SimVariable.AutopilotFlightDirectorBank, "AUTOPILOT FLIGHT DIRECTOR BANK" },
            { SimVariable.AutopilotPitchHold, "AUTOPILOT PITCH HOLD" },
            { SimVariable.AutopilotPitchHoldRef, "AUTOPILOT PITCH HOLD REF" },
            { SimVariable.AutopilotNavSelected, "AUTOPILOT NAV SELECTED" },
            { SimVariable.GpsDrivesNav1, "GPS DRIVES NAV1" },
            { SimVariable.AutothrottleActive, "AUTOTHROTTLE ACTIVE" },
            { SimVariable.AutopilotMaxBank, "AUTOPILOT MAX BANK" },
            { SimVariable.NumberOfCatapults, "NUMBER OF CATAPULTS" },
            { SimVariable.HoldbackBarInstalled, "HOLDBACK BAR INSTALLED" },
            { SimVariable.BlastShieldPosition, "BLAST SHIELD POSITION" },
            { SimVariable.CatapultStrokePosition, "CATAPULT STROKE POSITION" },
            { SimVariable.EngineControlSelect, "ENGINE CONTROL SELECT" },
            { SimVariable.NumberOfEngines, "NUMBER OF ENGINES" },
            { SimVariable.MaxRatedEngineRpm, "MAX RATED ENGINE RPM" },
            { SimVariable.PropellerAdvancedSelection, "PROPELLER ADVANCED SELECTION" },
            { SimVariable.ThrottleLowerLimit, "THROTTLE LOWER LIMIT" },
            { SimVariable.OilAmount, "OIL AMOUNT" },
            { SimVariable.EnginePrimer, "ENGINE PRIMER" },
            { SimVariable.EngineType, "ENGINE TYPE" },
            { SimVariable.EngRpmAnimationPercent, "ENG RPM ANIMATION PERCENT" },
            { SimVariable.FullThrottleThrustToWeightRatio, "FULL THROTTLE THRUST TO WEIGHT RATIO" },
            { SimVariable.PropRpm, "PROP RPM" },
            { SimVariable.PropMaxRpmPercent, "PROP MAX RPM PERCENT" },
            { SimVariable.PropThrust, "PROP THRUST" },
            { SimVariable.PropBeta, "PROP BETA" },
            { SimVariable.PropFeatheringInhibit, "PROP FEATHERING INHIBIT" },
            { SimVariable.PropFeathered, "PROP FEATHERED" },
            { SimVariable.PropSyncDeltaLever, "PROP SYNC DELTA LEVER" },
            { SimVariable.PropAutoFeatherArmed, "PROP AUTO FEATHER ARMED" },
            { SimVariable.PropFeatherSwitch, "PROP FEATHER SWITCH" },
            { SimVariable.PropAutoCruiseActive, "PROP AUTO CRUISE ACTIVE" },
            { SimVariable.PropRotationAngle, "PROP ROTATION ANGLE" },
            { SimVariable.PropBetaMax, "PROP BETA MAX" },
            { SimVariable.PropBetaMin, "PROP BETA MIN" },
            { SimVariable.PropBetaMinReverse, "PROP BETA MIN REVERSE" },
            { SimVariable.MasterIgnitionSwitch, "MASTER IGNITION SWITCH" },
            { SimVariable.EngCombustion, "ENG COMBUSTION" },
            { SimVariable.OldEngStarter, "OLD ENG STARTER" },
            { SimVariable.EngN1Rpm, "ENG N1 RPM" },
            { SimVariable.EngN2Rpm, "ENG N2 RPM" },
            { SimVariable.EngFuelFlowGph, "ENG FUEL FLOW GPH" },
            { SimVariable.EngFuelFlowPph, "ENG FUEL FLOW PPH" },
            { SimVariable.EngFuelFlowPphSsl, "ENG FUEL FLOW PPH SSL" },
            { SimVariable.EngTorque, "ENG TORQUE" },
            { SimVariable.EngAntiIce, "ENG ANTI ICE" },
            { SimVariable.EngPressureRatio, "ENG PRESSURE RATIO" },
            { SimVariable.EngPressureRatioGes, "ENG PRESSURE RATIO GES" },
            { SimVariable.EngExhaustGasTemperature, "ENG EXHAUST GAS TEMPERATURE" },
            { SimVariable.EngExhaustGasTemperatureGes, "ENG EXHAUST GAS TEMPERATURE GES" },
            { SimVariable.EngCylinderHeadTemperature, "ENG CYLINDER HEAD TEMPERATURE" },
            { SimVariable.EngOilTemperature, "ENG OIL TEMPERATURE" },
            { SimVariable.EngOilPressure, "ENG OIL PRESSURE" },
            { SimVariable.EngOilQuantity, "ENG OIL QUANTITY" },
            { SimVariable.EngHydraulicPressure, "ENG HYDRAULIC PRESSURE" },
            { SimVariable.EngHydraulicQuantity, "ENG HYDRAULIC QUANTITY" },
            { SimVariable.EngManifoldPressure, "ENG MANIFOLD PRESSURE" },
            { SimVariable.EngVibration, "ENG VIBRATION" },
            { SimVariable.EngRpmScaler, "ENG RPM SCALER" },
            { SimVariable.EngTurbineTemperature, "ENG TURBINE TEMPERATURE" },
            { SimVariable.EngTorquePercent, "ENG TORQUE PERCENT" },
            { SimVariable.EngFuelPressure, "ENG FUEL PRESSURE" },
            { SimVariable.EngElectricalLoad, "ENG ELECTRICAL LOAD" },
            { SimVariable.EngTransmissionPressure, "ENG TRANSMISSION PRESSURE" },
            { SimVariable.EngTransmissionTemperature, "ENG TRANSMISSION TEMPERATURE" },
            { SimVariable.EngRotorRpm, "ENG ROTOR RPM" },
            { SimVariable.EngFuelFlowBugPosition, "ENG FUEL FLOW BUG POSITION" },
            { SimVariable.EngMaxRpm, "ENG MAX RPM" },
            { SimVariable.EngOnFire, "ENG ON FIRE" },
            { SimVariable.GeneralEngCombustion, "GENERAL ENG COMBUSTION" },
            { SimVariable.GeneralEngMasterAlternator, "GENERAL ENG MASTER ALTERNATOR" },
            { SimVariable.GeneralEngFuelPumpSwitch, "GENERAL ENG FUEL PUMP SWITCH" },
            { SimVariable.GeneralEngFuelPumpOn, "GENERAL ENG FUEL PUMP ON" },
            { SimVariable.GeneralEngRpm, "GENERAL ENG RPM" },
            { SimVariable.GeneralEngPctMaxRpm, "GENERAL ENG PCT MAX RPM" },
            { SimVariable.GeneralEngMaxReachedRpm, "GENERAL ENG MAX REACHED RPM" },
            { SimVariable.GeneralEngThrottleLeverPosition, "GENERAL ENG THROTTLE LEVER POSITION" },
            { SimVariable.GeneralEngMixtureLeverPosition, "GENERAL ENG MIXTURE LEVER POSITION" },
            { SimVariable.GeneralEngPropellerLeverPosition, "GENERAL ENG PROPELLER LEVER POSITION" },
            { SimVariable.GeneralEngStarter, "GENERAL ENG STARTER" },
            { SimVariable.GeneralEngStarterActive, "GENERAL ENG STARTER ACTIVE" },
            { SimVariable.GeneralEngExhaustGasTemperature, "GENERAL ENG EXHAUST GAS TEMPERATURE" },
            { SimVariable.GeneralEngOilPressure, "GENERAL ENG OIL PRESSURE" },
            { SimVariable.GeneralEngOilLeakedPercent, "GENERAL ENG OIL LEAKED PERCENT" },
            { SimVariable.GeneralEngCombustionSoundPercent, "GENERAL ENG COMBUSTION SOUND PERCENT" },
            { SimVariable.GeneralEngDamagePercent, "GENERAL ENG DAMAGE PERCENT" },
            { SimVariable.GeneralEngOilTemperature, "GENERAL ENG OIL TEMPERATURE" },
            { SimVariable.GeneralEngFailed, "GENERAL ENG FAILED" },
            { SimVariable.GeneralEngGeneratorSwitch, "GENERAL ENG GENERATOR SWITCH" },
            { SimVariable.GeneralEngGeneratorActive, "GENERAL ENG GENERATOR ACTIVE" },
            { SimVariable.GeneralEngAntiIcePosition, "GENERAL ENG ANTI ICE POSITION" },
            { SimVariable.GeneralEngFuelValve, "GENERAL ENG FUEL VALVE" },
            { SimVariable.GeneralEngFuelPressure, "GENERAL ENG FUEL PRESSURE" },
            { SimVariable.GeneralEngElapsedTime, "GENERAL ENG ELAPSED TIME" },
            { SimVariable.GeneralEngFireDetected, "GENERAL ENG FIRE DETECTED" },
            { SimVariable.GeneralEngFuelUsedSinceStart, "GENERAL ENG FUEL USED SINCE START" },
            { SimVariable.RecipEngCowlFlapPosition, "RECIP ENG COWL FLAP POSITION" },
            { SimVariable.RecipEngPrimer, "RECIP ENG PRIMER" },
            { SimVariable.RecipEngManifoldPressure, "RECIP ENG MANIFOLD PRESSURE" },
            { SimVariable.RecipEngAlternateAirPosition, "RECIP ENG ALTERNATE AIR POSITION" },
            { SimVariable.RecipEngCoolantReservoirPercent, "RECIP ENG COOLANT RESERVOIR PERCENT" },
            { SimVariable.RecipEngLeftMagneto, "RECIP ENG LEFT MAGNETO" },
            { SimVariable.RecipEngRightMagneto, "RECIP ENG RIGHT MAGNETO" },
            { SimVariable.RecipEngBrakePower, "RECIP ENG BRAKE POWER" },
            { SimVariable.RecipEngStarterTorque, "RECIP ENG STARTER TORQUE" },
            { SimVariable.RecipEngTurbochargerFailed, "RECIP ENG TURBOCHARGER FAILED" },
            { SimVariable.RecipEngEmergencyBoostActive, "RECIP ENG EMERGENCY BOOST ACTIVE" },
            { SimVariable.RecipEngEmergencyBoostElapsedTime, "RECIP ENG EMERGENCY BOOST ELAPSED TIME" },
            { SimVariable.RecipEngWastegatePosition, "RECIP ENG WASTEGATE POSITION" },
            { SimVariable.RecipEngTurbineInletTemperature, "RECIP ENG TURBINE INLET TEMPERATURE" },
            { SimVariable.RecipEngCylinderHeadTemperature, "RECIP ENG CYLINDER HEAD TEMPERATURE" },
            { SimVariable.RecipEngRadiatorTemperature, "RECIP ENG RADIATOR TEMPERATURE" },
            { SimVariable.RecipEngFuelAvailable, "RECIP ENG FUEL AVAILABLE" },
            { SimVariable.RecipEngFuelFlow, "RECIP ENG FUEL FLOW" },
            { SimVariable.RecipEngFuelTankSelector, "RECIP ENG FUEL TANK SELECTOR" },
            { SimVariable.RecipEngFuelTanksUsed, "RECIP ENG FUEL TANKS USED" },
            { SimVariable.RecipEngFuelNumberTanksUsed, "RECIP ENG FUEL NUMBER TANKS USED" },
            { SimVariable.RecipEngDetonating, "RECIP ENG DETONATING" },
            { SimVariable.RecipEngCylinderHealth, "RECIP ENG CYLINDER HEALTH" },
            { SimVariable.RecipEngNumCylinders, "RECIP ENG NUM CYLINDERS" },
            { SimVariable.RecipEngNumCylindersFailed, "RECIP ENG NUM CYLINDERS FAILED" },
            { SimVariable.RecipCarburetorTemperature, "RECIP CARBURETOR TEMPERATURE" },
            { SimVariable.RecipMixtureRatio, "RECIP MIXTURE RATIO" },
            { SimVariable.RecipEngAntidetonationTankValve, "RECIP ENG ANTIDETONATION TANK VALVE" },
            { SimVariable.RecipEngAntidetonationTankQuantity, "RECIP ENG ANTIDETONATION TANK QUANTITY" },
            { SimVariable.RecipEngAntidetonationTankMaxQuantity, "RECIP ENG ANTIDETONATION TANK MAX QUANTITY" },
            { SimVariable.RecipEngNitrousTankValve, "RECIP ENG NITROUS TANK VALVE" },
            { SimVariable.RecipEngNitrousTankQuantity, "RECIP ENG NITROUS TANK QUANTITY" },
            { SimVariable.RecipEngNitrousTankMaxQuantity, "RECIP ENG NITROUS TANK MAX QUANTITY" },
            { SimVariable.TurbEngN1, "TURB ENG N1" },
            { SimVariable.TurbEngN2, "TURB ENG N2" },
            { SimVariable.TurbEngCorrectedN1, "TURB ENG CORRECTED N1" },
            { SimVariable.TurbEngCorrectedN2, "TURB ENG CORRECTED N2" },
            { SimVariable.TurbEngCorrectedFf, "TURB ENG CORRECTED FF" },
            { SimVariable.TurbEngMaxTorquePercent, "TURB ENG MAX TORQUE PERCENT" },
            { SimVariable.TurbEngPressureRatio, "TURB ENG PRESSURE RATIO" },
            { SimVariable.TurbEngItt, "TURB ENG ITT" },
            { SimVariable.TurbEngAfterburner, "TURB ENG AFTERBURNER" },
            { SimVariable.TurbEngAfterburnerStageActive, "TURB ENG AFTERBURNER STAGE ACTIVE" },
            { SimVariable.TurbEngAfterburnerPctActive, "TURB ENG AFTERBURNER PCT ACTIVE" },
            { SimVariable.TurbEngJetThrust, "TURB ENG JET THRUST" },
            { SimVariable.TurbEngBleedAir, "TURB ENG BLEED AIR" },
            { SimVariable.TurbEngTankSelector, "TURB ENG TANK SELECTOR" },
            { SimVariable.TurbEngTanksUsed, "TURB ENG TANKS USED" },
            { SimVariable.TurbEngNumTanksUsed, "TURB ENG NUM TANKS USED" },
            { SimVariable.TurbEngFuelFlowPph, "TURB ENG FUEL FLOW PPH" },
            { SimVariable.TurbEngFuelAvailable, "TURB ENG FUEL AVAILABLE" },
            { SimVariable.TurbEngPrimaryNozzlePercent, "TURB ENG PRIMARY NOZZLE PERCENT" },
            { SimVariable.TurbEngReverseNozzlePercent, "TURB ENG REVERSE NOZZLE PERCENT" },
            { SimVariable.TurbEngVibration, "TURB ENG VIBRATION" },
            { SimVariable.TurbEngIgnitionSwitch, "TURB ENG IGNITION SWITCH" },
            { SimVariable.TurbEngMasterStarterSwitch, "TURB ENG MASTER STARTER SWITCH" },
            { SimVariable.EngFailed, "ENG FAILED" },
            { SimVariable.PartialPanelAdf, "PARTIAL PANEL ADF" },
            { SimVariable.PartialPanelAirspeed, "PARTIAL PANEL AIRSPEED" },
            { SimVariable.PartialPanelAltimeter, "PARTIAL PANEL ALTIMETER" },
            { SimVariable.PartialPanelAttitude, "PARTIAL PANEL ATTITUDE" },
            { SimVariable.PartialPanelComm, "PARTIAL PANEL COMM" },
            { SimVariable.PartialPanelCompass, "PARTIAL PANEL COMPASS" },
            { SimVariable.PartialPanelElectrical, "PARTIAL PANEL ELECTRICAL" },
            { SimVariable.PartialPanelAvionics, "PARTIAL PANEL AVIONICS" },
            { SimVariable.PartialPanelEngine, "PARTIAL PANEL ENGINE" },
            { SimVariable.PartialPanelFuelIndicator, "PARTIAL PANEL FUEL INDICATOR" },
            { SimVariable.PartialPanelHeading, "PARTIAL PANEL HEADING" },
            { SimVariable.PartialPanelVerticalVelocity, "PARTIAL PANEL VERTICAL VELOCITY" },
            { SimVariable.PartialPanelTransponder, "PARTIAL PANEL TRANSPONDER" },
            { SimVariable.PartialPanelNav, "PARTIAL PANEL NAV" },
            { SimVariable.PartialPanelPitot, "PARTIAL PANEL PITOT" },
            { SimVariable.PartialPanelTurnCoordinator, "PARTIAL PANEL TURN COORDINATOR" },
            { SimVariable.PartialPanelVacuum, "PARTIAL PANEL VACUUM" },
            { SimVariable.FuelTankCenterLevel, "FUEL TANK CENTER LEVEL" },
            { SimVariable.FuelTankCenterCapacity, "FUEL TANK CENTER CAPACITY" },
            { SimVariable.FuelTankCenterQuantity, "FUEL TANK CENTER QUANTITY" },
            { SimVariable.FuelTankCenter2Level, "FUEL TANK CENTER2 LEVEL" },
            { SimVariable.FuelTankCenter2Capacity, "FUEL TANK CENTER2 CAPACITY" },
            { SimVariable.FuelTankCenter2Quantity, "FUEL TANK CENTER2 QUANTITY" },
            { SimVariable.FuelTankCenter3Level, "FUEL TANK CENTER3 LEVEL" },
            { SimVariable.FuelTankCenter3Capacity, "FUEL TANK CENTER3 CAPACITY" },
            { SimVariable.FuelTankCenter3Quantity, "FUEL TANK CENTER3 QUANTITY" },
            { SimVariable.FuelTankLeftMainLevel, "FUEL TANK LEFT MAIN LEVEL" },
            { SimVariable.FuelTankLeftMainCapacity, "FUEL TANK LEFT MAIN CAPACITY" },
            { SimVariable.FuelTankLeftMainQuantity, "FUEL TANK LEFT MAIN QUANTITY" },
            { SimVariable.FuelTankLeftAuxLevel, "FUEL TANK LEFT AUX LEVEL" },
            { SimVariable.FuelTankLeftAuxCapacity, "FUEL TANK LEFT AUX CAPACITY" },
            { SimVariable.FuelTankLeftAuxQuantity, "FUEL TANK LEFT AUX QUANTITY" },
            { SimVariable.FuelTankLeftTipLevel, "FUEL TANK LEFT TIP LEVEL" },
            { SimVariable.FuelTankLeftTipCapacity, "FUEL TANK LEFT TIP CAPACITY" },
            { SimVariable.FuelTankLeftTipQuantity, "FUEL TANK LEFT TIP QUANTITY" },
            { SimVariable.FuelLeftQuantity, "FUEL LEFT QUANTITY" },
            { SimVariable.FuelTankRightMainLevel, "FUEL TANK RIGHT MAIN LEVEL" },
            { SimVariable.FuelTankRightMainCapacity, "FUEL TANK RIGHT MAIN CAPACITY" },
            { SimVariable.FuelTankRightMainQuantity, "FUEL TANK RIGHT MAIN QUANTITY" },
            { SimVariable.FuelTankRightAuxLevel, "FUEL TANK RIGHT AUX LEVEL" },
            { SimVariable.FuelTankRightAuxCapacity, "FUEL TANK RIGHT AUX CAPACITY" },
            { SimVariable.FuelTankRightAuxQuantity, "FUEL TANK RIGHT AUX QUANTITY" },
            { SimVariable.FuelTankRightTipLevel, "FUEL TANK RIGHT TIP LEVEL" },
            { SimVariable.FuelTankRightTipCapacity, "FUEL TANK RIGHT TIP CAPACITY" },
            { SimVariable.FuelTankRightTipQuantity, "FUEL TANK RIGHT TIP QUANTITY" },
            { SimVariable.FuelRightQuantity, "FUEL RIGHT QUANTITY" },
            { SimVariable.FuelTankExternal1Level, "FUEL TANK EXTERNAL1 LEVEL" },
            { SimVariable.FuelTankExternal1Capacity, "FUEL TANK EXTERNAL1 CAPACITY" },
            { SimVariable.FuelTankExternal1Quantity, "FUEL TANK EXTERNAL1 QUANTITY" },
            { SimVariable.FuelTankExternal2Level, "FUEL TANK EXTERNAL2 LEVEL" },
            { SimVariable.FuelTankExternal2Capacity, "FUEL TANK EXTERNAL2 CAPACITY" },
            { SimVariable.FuelTankExternal2Quantity, "FUEL TANK EXTERNAL2 QUANTITY" },
            { SimVariable.FuelTotalQuantity, "FUEL TOTAL QUANTITY" },
            { SimVariable.FuelTotalCapacity, "FUEL TOTAL CAPACITY" },
            { SimVariable.FuelLeftCapacity, "FUEL LEFT CAPACITY" },
            { SimVariable.FuelRightCapacity, "FUEL RIGHT CAPACITY" },
            { SimVariable.FuelWeightPerGallon, "FUEL WEIGHT PER GALLON" },
            { SimVariable.FuelTankSelector, "FUEL TANK SELECTOR" },
            { SimVariable.FuelCrossFeed, "FUEL CROSS FEED" },
            { SimVariable.NumFuelSelectors, "NUM FUEL SELECTORS" },
            { SimVariable.FuelSelectedQuantityPercent, "FUEL SELECTED QUANTITY PERCENT" },
            { SimVariable.FuelSelectedQuantity, "FUEL SELECTED QUANTITY" },
            { SimVariable.FuelTotalQuantityWeight, "FUEL TOTAL QUANTITY WEIGHT" },
            { SimVariable.FuelSelectedTransferMode, "FUEL SELECTED TRANSFER MODE" },
            { SimVariable.FuelDumpSwitch, "FUEL DUMP SWITCH" },
            { SimVariable.FuelDumpActive, "FUEL DUMP ACTIVE" },
            { SimVariable.DroppableObjectsCount, "DROPPABLE OBJECTS COUNT" },
            { SimVariable.DroppableObjectsType, "DROPPABLE OBJECTS TYPE" },
            { SimVariable.DroppableObjectsUiName, "DROPPABLE OBJECTS UI NAME" },
            { SimVariable.WarningFuel, "WARNING FUEL" },
            { SimVariable.WarningFuelLeft, "WARNING FUEL LEFT" },
            { SimVariable.WarningFuelRight, "WARNING FUEL RIGHT" },
            { SimVariable.WarningVacuum, "WARNING VACUUM" },
            { SimVariable.WarningVacuumLeft, "WARNING VACUUM LEFT" },
            { SimVariable.WarningVacuumRight, "WARNING VACUUM RIGHT" },
            { SimVariable.WarningOilPressure, "WARNING OIL PRESSURE" },
            { SimVariable.WarningVoltage, "WARNING VOLTAGE" },
            { SimVariable.WarningLowHeight, "WARNING LOW HEIGHT" },
            { SimVariable.AutopilotAvailable, "AUTOPILOT AVAILABLE" },
            { SimVariable.FlapsAvailable, "FLAPS AVAILABLE" },
            { SimVariable.StallHornAvailable, "STALL HORN AVAILABLE" },
            { SimVariable.EngineMixureAvailable, "ENGINE MIXURE AVAILABLE" },
            { SimVariable.CarbHeatAvailable, "CARB HEAT AVAILABLE" },
            { SimVariable.SpoilerAvailable, "SPOILER AVAILABLE" },
            { SimVariable.StrobesAvailable, "STROBES AVAILABLE" },
            { SimVariable.PropTypeAvailable, "PROP TYPE AVAILABLE" },
            { SimVariable.ToeBrakesAvailable, "TOE BRAKES AVAILABLE" },
            { SimVariable.IsTailDragger, "IS TAIL DRAGGER" },
            { SimVariable.SystemsAvailable, "SYSTEMS AVAILABLE" },
            { SimVariable.InstrumentsAvailable, "INSTRUMENTS AVAILABLE" },
            { SimVariable.FuelPump, "FUEL PUMP" },
            { SimVariable.ManualFuelPumpHandle, "MANUAL FUEL PUMP HANDLE" },
            { SimVariable.AlternateStaticSourceOpen, "ALTERNATE STATIC SOURCE OPEN" },
            { SimVariable.BleedAirSourceControl, "BLEED AIR SOURCE CONTROL" },
            { SimVariable.ElectricalMasterBattery, "ELECTRICAL MASTER BATTERY" },
            { SimVariable.ElectricalOldChargingAmps, "ELECTRICAL OLD CHARGING AMPS" },
            { SimVariable.ElectricalTotalLoadAmps, "ELECTRICAL TOTAL LOAD AMPS" },
            { SimVariable.ElectricalBatteryLoad, "ELECTRICAL BATTERY LOAD" },
            { SimVariable.ElectricalBatteryVoltage, "ELECTRICAL BATTERY VOLTAGE" },
            { SimVariable.ElectricalMainBusVoltage, "ELECTRICAL MAIN BUS VOLTAGE" },
            { SimVariable.ElectricalMainBusAmps, "ELECTRICAL MAIN BUS AMPS" },
            { SimVariable.ElectricalAvionicsBusVoltage, "ELECTRICAL AVIONICS BUS VOLTAGE" },
            { SimVariable.ElectricalAvionicsBusAmps, "ELECTRICAL AVIONICS BUS AMPS" },
            { SimVariable.ElectricalHotBatteryBusVoltage, "ELECTRICAL HOT BATTERY BUS VOLTAGE" },
            { SimVariable.ElectricalHotBatteryBusAmps, "ELECTRICAL HOT BATTERY BUS AMPS" },
            { SimVariable.ElectricalBatteryBusVoltage, "ELECTRICAL BATTERY BUS VOLTAGE" },
            { SimVariable.ElectricalBatteryBusAmps, "ELECTRICAL BATTERY BUS AMPS" },
            { SimVariable.ElectricalGenaltBusVoltage, "ELECTRICAL GENALT BUS VOLTAGE" },
            { SimVariable.ElectricalGenaltBusAmps, "ELECTRICAL GENALT BUS AMPS" },
            { SimVariable.CircuitGeneralPanelOn, "CIRCUIT GENERAL PANEL ON" },
            { SimVariable.CircuitFlapMotorOn, "CIRCUIT FLAP MOTOR ON" },
            { SimVariable.CircuitGearMotorOn, "CIRCUIT GEAR MOTOR ON" },
            { SimVariable.CircuitAutopilotOn, "CIRCUIT AUTOPILOT ON" },
            { SimVariable.CircuitAvionicsOn, "CIRCUIT AVIONICS ON" },
            { SimVariable.CircuitPitotHeatOn, "CIRCUIT PITOT HEAT ON" },
            { SimVariable.CircuitPropSyncOn, "CIRCUIT PROP SYNC ON" },
            { SimVariable.CircuitAutoFeatherOn, "CIRCUIT AUTO FEATHER ON" },
            { SimVariable.CircuitAutoBrakesOn, "CIRCUIT AUTO BRAKES ON" },
            { SimVariable.CircuitStandyVacuumOn, "CIRCUIT STANDY VACUUM ON" },
            { SimVariable.CircuitStandbyVacuumOn, "CIRCUIT STANDBY VACUUM ON" },
            { SimVariable.CircuitMarkerBeaconOn, "CIRCUIT MARKER BEACON ON" },
            { SimVariable.CircuitGearWarningOn, "CIRCUIT GEAR WARNING ON" },
            { SimVariable.CircuitHydraulicPumpOn, "CIRCUIT HYDRAULIC PUMP ON" },
            { SimVariable.AmbientDensity, "AMBIENT DENSITY" },
            { SimVariable.AmbientTemperature, "AMBIENT TEMPERATURE" },
            { SimVariable.AmbientPressure, "AMBIENT PRESSURE" },
            { SimVariable.AmbientWindVelocity, "AMBIENT WIND VELOCITY" },
            { SimVariable.AmbientWindDirection, "AMBIENT WIND DIRECTION" },
            { SimVariable.AmbientWindX, "AMBIENT WIND X" },
            { SimVariable.AmbientWindY, "AMBIENT WIND Y" },
            { SimVariable.AmbientWindZ, "AMBIENT WIND Z" },
            { SimVariable.AmbientPrecipState, "AMBIENT PRECIP STATE" },
            { SimVariable.AmbientInCloud, "AMBIENT IN CLOUD" },
            { SimVariable.AmbientVisibility, "AMBIENT VISIBILITY" },
            { SimVariable.BarometerPressure, "BAROMETER PRESSURE" },
            { SimVariable.SeaLevelPressure, "SEA LEVEL PRESSURE" },
            { SimVariable.TotalAirTemperature, "TOTAL AIR TEMPERATURE" },
            { SimVariable.StandardAtmTemperature, "STANDARD ATM TEMPERATURE" },
            { SimVariable.AircraftWindX, "AIRCRAFT WIND X" },
            { SimVariable.AircraftWindY, "AIRCRAFT WIND Y" },
            { SimVariable.AircraftWindZ, "AIRCRAFT WIND Z" },
            { SimVariable.HydraulicPressure, "HYDRAULIC PRESSURE" },
            { SimVariable.HydraulicReservoirPercent, "HYDRAULIC RESERVOIR PERCENT" },
            { SimVariable.HydraulicSystemIntegrity, "HYDRAULIC SYSTEM INTEGRITY" },
            { SimVariable.HydraulicSwitch, "HYDRAULIC SWITCH" },
            { SimVariable.GearHydraulicPressure, "GEAR HYDRAULIC PRESSURE" },
            { SimVariable.ConcordeVisorNoseHandle, "CONCORDE VISOR NOSE HANDLE" },
            { SimVariable.ConcordeVisorPositionPercent, "CONCORDE VISOR POSITION PERCENT" },
            { SimVariable.ConcordeNoseAngle, "CONCORDE NOSE ANGLE" },
            { SimVariable.RadiosAvailable, "RADIOS AVAILABLE" },
            { SimVariable.ComTransmit, "COM TRANSMIT" },
            { SimVariable.ComReceiveAll, "COM RECEIVE ALL" },
            { SimVariable.ComRecieveAll, "COM RECIEVE ALL" },
            { SimVariable.NavSound, "NAV SOUND" },
            { SimVariable.DmeSound, "DME SOUND" },
            { SimVariable.AdfSound, "ADF SOUND" },
            { SimVariable.AdfCard, "ADF CARD" },
            { SimVariable.MarkerSound, "MARKER SOUND" },
            { SimVariable.ComAvailable, "COM AVAILABLE" },
            { SimVariable.ComActiveFrequency, "COM ACTIVE FREQUENCY" },
            { SimVariable.ComStandbyFrequency, "COM STANDBY FREQUENCY" },
            { SimVariable.ComStatus, "COM STATUS" },
            { SimVariable.ComTest, "COM TEST" },
            { SimVariable.TransponderAvailable, "TRANSPONDER AVAILABLE" },
            { SimVariable.TransponderCode, "TRANSPONDER CODE" },
            { SimVariable.AdfAvailable, "ADF AVAILABLE" },
            { SimVariable.AdfFrequency, "ADF FREQUENCY" },
            { SimVariable.AdfExtFrequency, "ADF EXT FREQUENCY" },
            { SimVariable.AdfActiveFrequency, "ADF ACTIVE FREQUENCY" },
            { SimVariable.AdfStandbyFrequency, "ADF STANDBY FREQUENCY" },
            { SimVariable.AdfLatlonalt, "ADF LATLONALT" },
            { SimVariable.AdfSignal, "ADF SIGNAL" },
            { SimVariable.AdfRadial, "ADF RADIAL" },
            { SimVariable.AdfIdent, "ADF IDENT" },
            { SimVariable.AdfName, "ADF NAME" },
            { SimVariable.NavAvailable, "NAV AVAILABLE" },
            { SimVariable.NavActiveFrequency, "NAV ACTIVE FREQUENCY" },
            { SimVariable.NavStandbyFrequency, "NAV STANDBY FREQUENCY" },
            { SimVariable.NavSignal, "NAV SIGNAL" },
            { SimVariable.NavIdent, "NAV IDENT" },
            { SimVariable.NavName, "NAV NAME" },
            { SimVariable.NavCodes, "NAV CODES" },
            { SimVariable.NavHasNav, "NAV HAS NAV" },
            { SimVariable.NavHasLocalizer, "NAV HAS LOCALIZER" },
            { SimVariable.NavHasDme, "NAV HAS DME" },
            { SimVariable.NavHasGlideSlope, "NAV HAS GLIDE SLOPE" },
            { SimVariable.NavBackCourseFlags, "NAV BACK COURSE FLAGS" },
            { SimVariable.NavMagvar, "NAV MAGVAR" },
            { SimVariable.NavRadial, "NAV RADIAL" },
            { SimVariable.NavRadialError, "NAV RADIAL ERROR" },
            { SimVariable.NavLocalizer, "NAV LOCALIZER" },
            { SimVariable.NavGlideSlope, "NAV GLIDE SLOPE" },
            { SimVariable.NavGlideSlopeError, "NAV GLIDE SLOPE ERROR" },
            { SimVariable.NavCdi, "NAV CDI" },
            { SimVariable.NavGsi, "NAV GSI" },
            { SimVariable.NavTofrom, "NAV TOFROM" },
            { SimVariable.NavGsFlag, "NAV GS FLAG" },
            { SimVariable.NavObs, "NAV OBS" },
            { SimVariable.NavDme, "NAV DME" },
            { SimVariable.NavDmespeed, "NAV DMESPEED" },
            { SimVariable.NavVorLatlonalt, "NAV VOR LATLONALT" },
            { SimVariable.NavGsLatlonalt, "NAV GS LATLONALT" },
            { SimVariable.NavDmeLatlonalt, "NAV DME LATLONALT" },
            { SimVariable.NavRelativeBearingToStation, "NAV RELATIVE BEARING TO STATION" },
            { SimVariable.MarkerBeaconState, "MARKER BEACON STATE" },
            { SimVariable.InnerMarker, "INNER MARKER" },
            { SimVariable.MiddleMarker, "MIDDLE MARKER" },
            { SimVariable.OuterMarker, "OUTER MARKER" },
            { SimVariable.InnerMarkerLatlonalt, "INNER MARKER LATLONALT" },
            { SimVariable.MiddleMarkerLatlonalt, "MIDDLE MARKER LATLONALT" },
            { SimVariable.OuterMarkerLatlonalt, "OUTER MARKER LATLONALT" },
            { SimVariable.SelectedDme, "SELECTED DME" },
            { SimVariable.Realism, "REALISM" },
            { SimVariable.AutoCoordination, "AUTO COORDINATION" },
            { SimVariable.UnlimitedFuel, "UNLIMITED FUEL" },
            { SimVariable.RealismCrashWithOthers, "REALISM CRASH WITH OTHERS" },
            { SimVariable.RealismCrashDetection, "REALISM CRASH DETECTION" },
            { SimVariable.ManualInstrumentLights, "MANUAL INSTRUMENT LIGHTS" },
            { SimVariable.TrueAirspeedSelected, "TRUE AIRSPEED SELECTED" },
            { SimVariable.AtcType, "ATC TYPE" },
            { SimVariable.AtcModel, "ATC MODEL" },
            { SimVariable.AtcHeavy, "ATC HEAVY" },
            { SimVariable.AtcId, "ATC ID" },
            { SimVariable.AtcAirline, "ATC AIRLINE" },
            { SimVariable.AtcFlightNumber, "ATC FLIGHT NUMBER" },
            { SimVariable.StructLatlonalt, "STRUCT LATLONALT" },
            { SimVariable.StructLatlonaltpbh, "STRUCT LATLONALTPBH" },
            { SimVariable.StructPbh32, "STRUCT PBH32" },
            { SimVariable.StructDamagevisible, "STRUCT DAMAGEVISIBLE" },
            { SimVariable.StructSurfaceRelativeVelocity, "STRUCT SURFACE RELATIVE VELOCITY" },
            { SimVariable.StructWorldvelocity, "STRUCT WORLDVELOCITY" },
            { SimVariable.StructWorldRotationVelocity, "STRUCT WORLD ROTATION VELOCITY" },
            { SimVariable.StructBodyVelocity, "STRUCT BODY VELOCITY" },
            { SimVariable.StructBodyRotationVelocity, "STRUCT BODY ROTATION VELOCITY" },
            { SimVariable.StructBodyRotationAcceleration, "STRUCT BODY ROTATION ACCELERATION" },
            { SimVariable.StructWorldAcceleration, "STRUCT WORLD ACCELERATION" },
            { SimVariable.StructEnginePosition, "STRUCT ENGINE POSITION" },
            { SimVariable.StructAmbientWind, "STRUCT AMBIENT WIND" },
            { SimVariable.StructRealismVars, "STRUCT REALISM VARS" },
            { SimVariable.StrucHeadingHoldPidConsts, "STRUC HEADING HOLD PID CONSTS" },
            { SimVariable.StrucAirspeedHoldPidConsts, "STRUC AIRSPEED HOLD PID CONSTS" },
            { SimVariable.StructEyepointDynamicAngle, "STRUCT EYEPOINT DYNAMIC ANGLE" },
            { SimVariable.StructEyepointDynamicOffset, "STRUCT EYEPOINT DYNAMIC OFFSET" },
            { SimVariable.PitotHeat, "PITOT HEAT" },
            { SimVariable.PitotIcePct, "PITOT ICE PCT" },
            { SimVariable.SmokeEnable, "SMOKE ENABLE" },
            { SimVariable.SmokesystemAvailable, "SMOKESYSTEM AVAILABLE" },
            { SimVariable.GForce, "G FORCE" },
            { SimVariable.SemibodyLoadfactorX, "SEMIBODY LOADFACTOR X" },
            { SimVariable.SemibodyLoadfactorY, "SEMIBODY LOADFACTOR Y" },
            { SimVariable.SemibodyLoadfactorZ, "SEMIBODY LOADFACTOR Z" },
            { SimVariable.SemibodyLoadfactorYdot, "SEMIBODY LOADFACTOR YDOT" },
            { SimVariable.MaxGForce, "MAX G FORCE" },
            { SimVariable.MinGForce, "MIN G FORCE" },
            { SimVariable.SuctionPressure, "SUCTION PRESSURE" },
            { SimVariable.RadInsSwitch, "RAD INS SWITCH" },
            { SimVariable.TypicalDescentRate, "TYPICAL DESCENT RATE" },
            { SimVariable.VisualModelRadius, "VISUAL MODEL RADIUS" },
            { SimVariable.SimulatedRadius, "SIMULATED RADIUS" },
            { SimVariable.IsUserSim, "IS USER SIM" },
            { SimVariable.Controllable, "CONTROLLABLE" },
            { SimVariable.HeadingIndicator, "HEADING INDICATOR" },
            { SimVariable.Title, "TITLE" },
            { SimVariable.Category, "CATEGORY" },
            { SimVariable.SimDisabled, "SIM DISABLED" },
            { SimVariable.PropDeiceSwitch, "PROP DEICE SWITCH" },
            { SimVariable.StructuralDeiceSwitch, "STRUCTURAL DEICE SWITCH" },
            { SimVariable.StructuralIcePct, "STRUCTURAL ICE PCT" },
            { SimVariable.ArtificialGroundElevation, "ARTIFICIAL GROUND ELEVATION" },
            { SimVariable.SurfaceInfoValid, "SURFACE INFO VALID" },
            { SimVariable.SurfaceType, "SURFACE TYPE" },
            { SimVariable.SurfaceCondition, "SURFACE CONDITION" },
            { SimVariable.PushbackState, "PUSHBACK STATE" },
            { SimVariable.PushbackAngle, "PUSHBACK ANGLE" },
            { SimVariable.PushbackContactx, "PUSHBACK CONTACTX" },
            { SimVariable.PushbackContacty, "PUSHBACK CONTACTY" },
            { SimVariable.PushbackContactz, "PUSHBACK CONTACTZ" },
            { SimVariable.PushbackWait, "PUSHBACK WAIT" },
            { SimVariable.HsiCdiNeedle, "HSI CDI NEEDLE" },
            { SimVariable.HsiGsiNeedle, "HSI GSI NEEDLE" },
            { SimVariable.HsiCdiNeedleValid, "HSI CDI NEEDLE VALID" },
            { SimVariable.HsiGsiNeedleValid, "HSI GSI NEEDLE VALID" },
            { SimVariable.HsiTfFlags, "HSI TF FLAGS" },
            { SimVariable.HsiBearing, "HSI BEARING" },
            { SimVariable.HsiBearingValid, "HSI BEARING VALID" },
            { SimVariable.HsiHasLocalizer, "HSI HAS LOCALIZER" },
            { SimVariable.HsiSpeed, "HSI SPEED" },
            { SimVariable.HsiDistance, "HSI DISTANCE" },
            { SimVariable.HsiStationIdent, "HSI STATION IDENT" },
            { SimVariable.IsSlewActive, "IS SLEW ACTIVE" },
            { SimVariable.IsSlewAllowed, "IS SLEW ALLOWED" },
            { SimVariable.AtcSuggestedMinRwyTakeoff, "ATC SUGGESTED MIN RWY TAKEOFF" },
            { SimVariable.AtcSuggestedMinRwyLanding, "ATC SUGGESTED MIN RWY LANDING" },
            { SimVariable.YawStringAngle, "YAW STRING ANGLE" },
            { SimVariable.YawStringPctExtended, "YAW STRING PCT EXTENDED" },
            { SimVariable.InductorCompassPercentDeviation, "INDUCTOR COMPASS PERCENT DEVIATION" },
            { SimVariable.InductorCompassHeadingRef, "INDUCTOR COMPASS HEADING REF" },
            { SimVariable.AnemometerPctRpm, "ANEMOMETER PCT RPM" },
            { SimVariable.GpsPositionLat, "GPS POSITION LAT" },
            { SimVariable.GpsPositionLon, "GPS POSITION LON" },
            { SimVariable.GpsPositionAlt, "GPS POSITION ALT" },
            { SimVariable.GpsMagvar, "GPS MAGVAR" },
            { SimVariable.GpsIsActiveFlightPlan, "GPS IS ACTIVE FLIGHT PLAN" },
            { SimVariable.GpsIsActiveWayPoint, "GPS IS ACTIVE WAY POINT" },
            { SimVariable.GpsIsArrived, "GPS IS ARRIVED" },
            { SimVariable.GpsIsDirecttoFlightplan, "GPS IS DIRECTTO FLIGHTPLAN" },
            { SimVariable.GpsGroundSpeed, "GPS GROUND SPEED" },
            { SimVariable.GpsGroundTrueHeading, "GPS GROUND TRUE HEADING" },
            { SimVariable.GpsGroundMagneticTrack, "GPS GROUND MAGNETIC TRACK" },
            { SimVariable.GpsGroundTrueTrack, "GPS GROUND TRUE TRACK" },
            { SimVariable.GpsEte, "GPS ETE" },
            { SimVariable.GpsEta, "GPS ETA" },
            { SimVariable.GpsWpDistance, "GPS WP DISTANCE" },
            { SimVariable.GpsWpBearing, "GPS WP BEARING" },
            { SimVariable.GpsWpTrueBearing, "GPS WP TRUE BEARING" },
            { SimVariable.GpsWpCrossTrk, "GPS WP CROSS TRK" },
            { SimVariable.GpsWpDesiredTrack, "GPS WP DESIRED TRACK" },
            { SimVariable.GpsWpTrueReqHdg, "GPS WP TRUE REQ HDG" },
            { SimVariable.GpsWpVerticalSpeed, "GPS WP VERTICAL SPEED" },
            { SimVariable.GpsWpTrackAngleError, "GPS WP TRACK ANGLE ERROR" },
            { SimVariable.GpsWpNextId, "GPS WP NEXT ID" },
            { SimVariable.GpsWpNextLat, "GPS WP NEXT LAT" },
            { SimVariable.GpsWpNextLon, "GPS WP NEXT LON" },
            { SimVariable.GpsWpNextAlt, "GPS WP NEXT ALT" },
            { SimVariable.GpsWpPrevValid, "GPS WP PREV VALID" },
            { SimVariable.GpsWpPrevId, "GPS WP PREV ID" },
            { SimVariable.GpsWpPrevLat, "GPS WP PREV LAT" },
            { SimVariable.GpsWpPrevLon, "GPS WP PREV LON" },
            { SimVariable.GpsWpPrevAlt, "GPS WP PREV ALT" },
            { SimVariable.GpsWpEte, "GPS WP ETE" },
            { SimVariable.GpsWpEta, "GPS WP ETA" },
            { SimVariable.GpsCourseToSteer, "GPS COURSE TO STEER" },
            { SimVariable.GpsFlightPlanWpIndex, "GPS FLIGHT PLAN WP INDEX" },
            { SimVariable.GpsFlightPlanWpCount, "GPS FLIGHT PLAN WP COUNT" },
            { SimVariable.GpsIsActiveWpLocked, "GPS IS ACTIVE WP LOCKED" },
            { SimVariable.GpsIsApproachLoaded, "GPS IS APPROACH LOADED" },
            { SimVariable.GpsIsApproachActive, "GPS IS APPROACH ACTIVE" },
            { SimVariable.GpsApproachMode, "GPS APPROACH MODE" },
            { SimVariable.GpsApproachWpType, "GPS APPROACH WP TYPE" },
            { SimVariable.GpsApproachIsWpRunway, "GPS APPROACH IS WP RUNWAY" },
            { SimVariable.GpsApproachSegmentType, "GPS APPROACH SEGMENT TYPE" },
            { SimVariable.GpsApproachAirportId, "GPS APPROACH AIRPORT ID" },
            { SimVariable.GpsApproachApproachIndex, "GPS APPROACH APPROACH INDEX" },
            { SimVariable.GpsApproachApproachId, "GPS APPROACH APPROACH ID" },
            { SimVariable.GpsApproachApproachType, "GPS APPROACH APPROACH TYPE" },
            { SimVariable.GpsApproachTransitionIndex, "GPS APPROACH TRANSITION INDEX" },
            { SimVariable.GpsApproachTransitionId, "GPS APPROACH TRANSITION ID" },
            { SimVariable.GpsApproachIsFinal, "GPS APPROACH IS FINAL" },
            { SimVariable.GpsApproachIsMissed, "GPS APPROACH IS MISSED" },
            { SimVariable.GpsApproachTimezoneDeviation, "GPS APPROACH TIMEZONE DEVIATION" },
            { SimVariable.GpsApproachWpIndex, "GPS APPROACH WP INDEX" },
            { SimVariable.GpsApproachWpCount, "GPS APPROACH WP COUNT" },
            { SimVariable.GpsTargetDistance, "GPS TARGET DISTANCE" },
            { SimVariable.GpsTargetAltitude, "GPS TARGET ALTITUDE" },
            { SimVariable.UserInputEnabled, "USER INPUT ENABLED" },
            { SimVariable.RotorBrakeHandlePos, "ROTOR BRAKE HANDLE POS" },
            { SimVariable.RotorBrakeActive, "ROTOR BRAKE ACTIVE" },
            { SimVariable.RotorClutchSwitchPos, "ROTOR CLUTCH SWITCH POS" },
            { SimVariable.RotorClutchActive, "ROTOR CLUTCH ACTIVE" },
            { SimVariable.RotorTemperature, "ROTOR TEMPERATURE" },
            { SimVariable.RotorChipDetected, "ROTOR CHIP DETECTED" },
            { SimVariable.RotorGovSwitchPos, "ROTOR GOV SWITCH POS" },
            { SimVariable.RotorGovActive, "ROTOR GOV ACTIVE" },
            { SimVariable.RotorLateralTrimPct, "ROTOR LATERAL TRIM PCT" },
            { SimVariable.RotorRpmPct, "ROTOR RPM PCT" },
            { SimVariable.RotorRotationAngle, "ROTOR ROTATION ANGLE" },
            { SimVariable.CollectivePosition, "COLLECTIVE POSITION" },
            { SimVariable.DiskPitchAngle, "DISK PITCH ANGLE" },
            { SimVariable.DiskBankAngle, "DISK BANK ANGLE" },
            { SimVariable.DiskPitchPct, "DISK PITCH PCT" },
            { SimVariable.DiskBankPct, "DISK BANK PCT" },
            { SimVariable.DiskConingPct, "DISK CONING PCT" },
            { SimVariable.GearDamageBySpeed, "GEAR DAMAGE BY SPEED" },
            { SimVariable.GearSpeedExceeded, "GEAR SPEED EXCEEDED" },
            { SimVariable.FlapDamageBySpeed, "FLAP DAMAGE BY SPEED" },
            { SimVariable.FlapSpeedExceeded, "FLAP SPEED EXCEEDED" },
            { SimVariable.EstimatedCruiseSpeed, "ESTIMATED CRUISE SPEED" },
            { SimVariable.EstimatedFuelFlow, "ESTIMATED FUEL FLOW" },
            { SimVariable.EyepointPosition, "EYEPOINT POSITION" },
            { SimVariable.NavVorLlaf64, "NAV VOR LLAF64" },
            { SimVariable.NavGsLlaf64, "NAV GS LLAF64" },
            { SimVariable.NavRawGlideSlope, "NAV RAW GLIDE SLOPE" },
            { SimVariable.WindshieldRainEffectAvailable, "WINDSHIELD RAIN EFFECT AVAILABLE" },
            { SimVariable.StaticCgToGround, "STATIC CG TO GROUND" },
            { SimVariable.StaticPitch, "STATIC PITCH" },
            { SimVariable.CrashSequence, "CRASH SEQUENCE" },
            { SimVariable.CrashFlag, "CRASH FLAG" },
            { SimVariable.ApplyHeatToSystems, "APPLY HEAT TO SYSTEMS" },
            { SimVariable.TowReleaseHandle, "TOW RELEASE HANDLE" },
            { SimVariable.TowConnection, "TOW CONNECTION" },
            { SimVariable.ApuPctRpm, "APU PCT RPM" },
            { SimVariable.ApuPctStarter, "APU PCT STARTER" },
            { SimVariable.ApuVolts, "APU VOLTS" },
            { SimVariable.ApuGeneratorSwitch, "APU GENERATOR SWITCH" },
            { SimVariable.ApuGeneratorActive, "APU GENERATOR ACTIVE" },
            { SimVariable.ApuOnFireDetected, "APU ON FIRE DETECTED" },
            { SimVariable.PressurizationCabinAltitude, "PRESSURIZATION CABIN ALTITUDE" },
            { SimVariable.PressurizationCabinAltitudeGoal, "PRESSURIZATION CABIN ALTITUDE GOAL" },
            { SimVariable.PressurizationCabinAltitudeRate, "PRESSURIZATION CABIN ALTITUDE RATE" },
            { SimVariable.PressurizationPressureDifferential, "PRESSURIZATION PRESSURE DIFFERENTIAL" },
            { SimVariable.PressurizationDumpSwitch, "PRESSURIZATION DUMP SWITCH" },
            { SimVariable.FireBottleSwitch, "FIRE BOTTLE SWITCH" },
            { SimVariable.FireBottleDischarged, "FIRE BOTTLE DISCHARGED" },
            { SimVariable.CabinNoSmokingAlertSwitch, "CABIN NO SMOKING ALERT SWITCH" },
            { SimVariable.CabinSeatbeltsAlertSwitch, "CABIN SEATBELTS ALERT SWITCH" },
            { SimVariable.GpwsWarning, "GPWS WARNING" },
            { SimVariable.GpwsSystemActive, "GPWS SYSTEM ACTIVE" },
            { SimVariable.IsLatitudeLongitudeFreezeOn, "IS LATITUDE LONGITUDE FREEZE ON" },
            { SimVariable.IsAltitudeFreezeOn, "IS ALTITUDE FREEZE ON" },
            { SimVariable.IsAttitudeFreezeOn, "IS ATTITUDE FREEZE ON" },
            { SimVariable.NumSlingCables, "NUM SLING CABLES" },
            { SimVariable.SlingObjectAttached, "SLING OBJECT ATTACHED" },
            { SimVariable.SlingCableBroken, "SLING CABLE BROKEN" },
            { SimVariable.SlingCableExtendedLength, "SLING CABLE EXTENDED LENGTH" },
            { SimVariable.SlingActivePayloadStation, "SLING ACTIVE PAYLOAD STATION" },
            { SimVariable.SlingHoistPercentDeployed, "SLING HOIST PERCENT DEPLOYED" },
            { SimVariable.SlingHoistSwitch, "SLING HOIST SWITCH" },
            { SimVariable.SlingHookInPickupMode, "SLING HOOK IN PICKUP MODE" },
            { SimVariable.IsAttachedToSling, "IS ATTACHED TO SLING" },
            { SimVariable.CableCaughtByTailhook, "CABLE CAUGHT BY TAILHOOK" },
            { SimVariable.ExternalSystemValue, "EXTERNAL SYSTEM VALUE" },
            { SimVariable.AnnunciatorSwitch, "ANNUNCIATOR SWITCH" },
            { SimVariable.AutobrakesActive, "AUTOBRAKES ACTIVE" },
            { SimVariable.RejectedTakeoffBrakesActive, "REJECTED TAKEOFF BRAKES ACTIVE" },
            { SimVariable.ShutoffValvePulled, "SHUTOFF VALVE PULLED" },
            { SimVariable.LightPotentiometer, "LIGHT POTENTIOMETER" },
            { SimVariable.FakeAcLwr, "FAKE AC LWR" },
            { SimVariable.FakeAcUpr, "FAKE AC UPR" },
            { SimVariable.FakeAcTrimL, "FAKE AC TRIM L" },
            { SimVariable.FakeAcTrimR, "FAKE AC TRIM R" },
            { SimVariable.FakeWindowHeatL, "FAKE WINDOW HEAT L" },
            { SimVariable.FakeWindowHeatR, "FAKE WINDOW HEAT R" },
            { SimVariable.FakeBusTie, "FAKE BUS TIE" },
            { SimVariable.FakeExtPwr, "FAKE EXT PWR" },
            { SimVariable.FakeGenCont, "FAKE GEN CONT" },
            { SimVariable.FakeUtilPwrL, "FAKE UTIL PWR L" },
            { SimVariable.FakeUtilPwrR, "FAKE UTIL PWR R" },
            { SimVariable.FakeCrtTankPumpL, "FAKE CRT TANK PUMP L" },
            { SimVariable.FakeCrtTankPumpR, "FAKE CRT TANK PUMP R" },
            { SimVariable.FakeFuelMainAft, "FAKE FUEL MAIN AFT" },
            { SimVariable.FakeFuelMainFwd, "FAKE FUEL MAIN FWD" },
            { SimVariable.FakeFuelOvrdAft, "FAKE FUEL OVRD AFT" },
            { SimVariable.FakeFuelOvrdFwd, "FAKE FUEL OVRD FWD" },
            { SimVariable.FakeStabTankPumpL, "FAKE STAB TANK PUMP L" },
            { SimVariable.FakeStabTankPumpR, "FAKE STAB TANK PUMP R" },
            { SimVariable.FakeHydPumpSwitch, "FAKE HYD PUMP SWITCH" },
            { SimVariable.FakeO2YdLower, "FAKE O2 YD LOWER" },
            { SimVariable.FakeO2YdUpper, "FAKE O2 YD UPPER" },
            { SimVariable.FakeApuBleed, "FAKE APU BLEED" },
            { SimVariable.FakeBleed, "FAKE BLEED" },
            { SimVariable.FakeIsolationValveL, "FAKE ISOLATION VALVE L" },
            { SimVariable.FakeIsolationValveR, "FAKE ISOLATION VALVE R" },
            { SimVariable.FakeAcFltDeck, "FAKE AC FLT DECK" },
            { SimVariable.FakeAcPassTemp, "FAKE AC PASS TEMP" },
            { SimVariable.FakeStandbyPower, "FAKE STANDBY POWER" },
            { SimVariable.FakeDemandPumpSel, "FAKE DEMAND PUMP SEL" },
            { SimVariable.FakeIrsC, "FAKE IRS C" },
            { SimVariable.FakeIrsL, "FAKE IRS L" },
            { SimVariable.FakeIrsR, "FAKE IRS R" },
            { SimVariable.FakeAntiIceNacelle, "FAKE ANTI ICE NACELLE" },
            { SimVariable.FakeAntiIceWing, "FAKE ANTI ICE WING" },
            { SimVariable.FakeOutflowValves, "FAKE OUTFLOW VALVES" },
            { SimVariable.FakeXfeed, "FAKE XFEED" },
            { SimVariable.FakeEec, "FAKE EEC" },
            { SimVariable.FakePack, "FAKE PACK" },
            { SimVariable.FakeEmergLights, "FAKE EMERG LIGHTS" },
            { SimVariable.FakeTrimStab, "FAKE TRIM STAB" },
            { SimVariable.FakeCargoArmAft, "FAKE CARGO ARM AFT" },
            { SimVariable.FakeXpndr, "FAKE XPNDR" },
            { SimVariable.FakeIdent, "FAKE IDENT" },
            { SimVariable.FakeNoSmoking, "FAKE NO SMOKING" },
            { SimVariable.FakeSeatbelts, "FAKE SEATBELTS" },
            { SimVariable.FakeCargoTemp, "FAKE CARGO TEMP" },
            { SimVariable.FakeEmergencyLight, "FAKE EMERGENCY LIGHT" },
            { SimVariable.AutopilotDisengaged, "AUTOPILOT DISENGAGED" },
            { SimVariable.FakeApuGenSwitch, "FAKE APU GEN SWITCH" },
            { SimVariable.BreakerAvnfan, "BREAKER AVNFAN" },
            { SimVariable.BreakerAutopilot, "BREAKER AUTOPILOT" },
            { SimVariable.BreakerGps, "BREAKER GPS" },
            { SimVariable.BreakerNavcom1, "BREAKER NAVCOM1" },
            { SimVariable.BreakerNavcom2, "BREAKER NAVCOM2" },
            { SimVariable.BreakerNavcom3, "BREAKER NAVCOM3" },
            { SimVariable.BreakerAdf, "BREAKER ADF" },
            { SimVariable.BreakerXpndr, "BREAKER XPNDR" },
            { SimVariable.BreakerFlap, "BREAKER FLAP" },
            { SimVariable.BreakerInst, "BREAKER INST" },
            { SimVariable.BreakerAvnbus1, "BREAKER AVNBUS1" },
            { SimVariable.BreakerAvnbus2, "BREAKER AVNBUS2" },
            { SimVariable.BreakerTurncoord, "BREAKER TURNCOORD" },
            { SimVariable.BreakerInstlts, "BREAKER INSTLTS" },
            { SimVariable.BreakerAltfld, "BREAKER ALTFLD" },
            { SimVariable.BreakerWarn, "BREAKER WARN" },
            { SimVariable.BreakerLtsPwr, "BREAKER LTS PWR" },
            { SimVariable.PilotTransmitterType, "PILOT TRANSMITTER TYPE" },
            { SimVariable.CopilotTransmitterType, "COPILOT TRANSMITTER TYPE" },
            { SimVariable.PilotTransmitting, "PILOT TRANSMITTING" },
            { SimVariable.CopilotTransmitting, "COPILOT TRANSMITTING" },
            { SimVariable.SpeakerActive, "SPEAKER ACTIVE" },
            { SimVariable.IntercomSystemActive, "INTERCOM SYSTEM ACTIVE" },
            { SimVariable.AudioPanelVolume, "AUDIO PANEL VOLUME" },
            { SimVariable.MarkerBeaconSensitivityHigh, "MARKER BEACON SENSITIVITY HIGH" },
            { SimVariable.MarkerBeaconTestMute, "MARKER BEACON TEST MUTE" },
            { SimVariable.IntercomMode, "INTERCOM MODE" },
            { SimVariable.ComReceive, "COM RECEIVE" },
            { SimVariable.AutopilotAltitudeArm, "AUTOPILOT ALTITUDE ARM" },
            { SimVariable.ComVolume, "COM VOLUME" },
            { SimVariable.NavVolume, "NAV VOLUME" },
            { SimVariable.AtcClearedIfr, "ATC CLEARED IFR" },
            { SimVariable.AtcIfrFpToRequest, "ATC IFR FP TO REQUEST" },
            { SimVariable.AtcRunwaySelected, "ATC RUNWAY SELECTED" },
            { SimVariable.AtcTaxipathDistance, "ATC TAXIPATH DISTANCE" },
            { SimVariable.AtcRunwayStartDistance, "ATC RUNWAY START DISTANCE" },
            { SimVariable.AtcRunwayEndDistance, "ATC RUNWAY END DISTANCE" },
            { SimVariable.AtcRunwayDistance, "ATC RUNWAY DISTANCE" },
            { SimVariable.AtcRunwayRelativePositionX, "ATC RUNWAY RELATIVE POSITION X" },
            { SimVariable.AtcRunwayRelativePositionY, "ATC RUNWAY RELATIVE POSITION Y" },
            { SimVariable.AtcRunwayRelativePositionZ, "ATC RUNWAY RELATIVE POSITION Z" },
            { SimVariable.AtcRunwayTdpointRelativePositionX, "ATC RUNWAY TDPOINT RELATIVE POSITION X" },
            { SimVariable.AtcRunwayTdpointRelativePositionY, "ATC RUNWAY TDPOINT RELATIVE POSITION Y" },
            { SimVariable.AtcRunwayTdpointRelativePositionZ, "ATC RUNWAY TDPOINT RELATIVE POSITION Z" },
            { SimVariable.AtcRunwayHeadingDegreesTrue, "ATC RUNWAY HEADING DEGREES TRUE" },
            { SimVariable.AtcRunwayLength, "ATC RUNWAY LENGTH" },
            { SimVariable.AtcRunwayWidth, "ATC RUNWAY WIDTH" },
            { SimVariable.AtcRunwayAirportName, "ATC RUNWAY AIRPORT NAME" },
            { SimVariable.SlopeToAtcRunway, "SLOPE TO ATC RUNWAY" },
            { SimVariable.AtcClearedTakeoff, "ATC CLEARED TAKEOFF" },
            { SimVariable.AtcClearedLanding, "ATC CLEARED LANDING" },
            { SimVariable.AtcClearedTaxi, "ATC CLEARED TAXI" },
            { SimVariable.OnAnyRunway, "ON ANY RUNWAY" },
            { SimVariable.AtcFlightplanDiffHeading, "ATC FLIGHTPLAN DIFF HEADING" },
            { SimVariable.AtcFlightplanDiffAlt, "ATC FLIGHTPLAN DIFF ALT" },
            { SimVariable.AtcFlightplanDiffDistance, "ATC FLIGHTPLAN DIFF DISTANCE" },
            { SimVariable.AtcPreviousWaypointAltitude, "ATC PREVIOUS WAYPOINT ALTITUDE" },
            { SimVariable.AtcCurrentWaypointAltitude, "ATC CURRENT WAYPOINT ALTITUDE" },
            { SimVariable.AssistanceLandingEnabled, "ASSISTANCE LANDING ENABLED" },
            { SimVariable.Com1StoredFrequency, "COM1 STORED FREQUENCY" },
            { SimVariable.Com2StoredFrequency, "COM2 STORED FREQUENCY" },
            { SimVariable.Com3StoredFrequency, "COM3 STORED FREQUENCY" },
            { SimVariable.RudderTrimDisabled, "RUDDER TRIM DISABLED" },
            { SimVariable.AileronTrimDisabled, "AILERON TRIM DISABLED" },
            { SimVariable.ElevatorTrimDisabled, "ELEVATOR TRIM DISABLED" },
            { SimVariable.PlaneTouchdownLatitude, "PLANE TOUCHDOWN LATITUDE" },
            { SimVariable.PlaneTouchdownLongitude, "PLANE TOUCHDOWN LONGITUDE" },
            { SimVariable.PlaneTouchdownPitchDegrees, "PLANE TOUCHDOWN PITCH DEGREES" },
            { SimVariable.PlaneTouchdownBankDegrees, "PLANE TOUCHDOWN BANK DEGREES" },
            { SimVariable.PlaneTouchdownHeadingDegreesMagnetic, "PLANE TOUCHDOWN HEADING DEGREES MAGNETIC" },
            { SimVariable.PlaneTouchdownHeadingDegreesTrue, "PLANE TOUCHDOWN HEADING DEGREES TRUE" },
            { SimVariable.PlaneTouchdownNormalVelocity, "PLANE TOUCHDOWN NORMAL VELOCITY" },
            { SimVariable.TurbEngIgnitionSwitchEx1, "TURB ENG IGNITION SWITCH EX1" },
            { SimVariable.TurbEngIsIgniting, "TURB ENG IS IGNITING" },
            { SimVariable.PlaneInParkingState, "PLANE IN PARKING STATE" },
            { SimVariable.EltActivated, "ELT ACTIVATED" },
            { SimVariable.RecipEngEngineMasterSwitch, "RECIP ENG ENGINE MASTER SWITCH" },
            { SimVariable.RecipEngGlowPlugActive, "RECIP ENG GLOW PLUG ACTIVE" },
            { SimVariable.LightGlareshield, "LIGHT GLARESHIELD" },
            { SimVariable.LightPedestral, "LIGHT PEDESTRAL" },
            { SimVariable.LightGlareshieldOn, "LIGHT GLARESHIELD ON" },
            { SimVariable.LightPedestralOn, "LIGHT PEDESTRAL ON" },
            { SimVariable.CircuitNavcom1On, "CIRCUIT NAVCOM1 ON" },
            { SimVariable.CircuitNavcom2On, "CIRCUIT NAVCOM2 ON" },
            { SimVariable.CircuitNavcom3On, "CIRCUIT NAVCOM3 ON" },
            { SimVariable.AirspeedTrueRaw, "AIRSPEED TRUE RAW" },
            { SimVariable.GeneralEngFuelPumpSwitchEx1, "GENERAL ENG FUEL PUMP SWITCH EX1" },
            { SimVariable.FuelTransferPumpOn, "FUEL TRANSFER PUMP ON" },
            { SimVariable.IsAnyInteriorLightOn, "IS ANY INTERIOR LIGHT ON" },
            { SimVariable.GpsFlightplanTotalDistance, "GPS FLIGHTPLAN TOTAL DISTANCE" },
            { SimVariable.CircuitOn, "CIRCUIT ON" },
            { SimVariable.CircuitSwitchOn, "CIRCUIT SWITCH ON" },
            { SimVariable.BusLookupIndex, "BUS LOOKUP INDEX" },
            { SimVariable.BusConnectionOn, "BUS CONNECTION ON" },
            { SimVariable.BatteryConnectionOn, "BATTERY CONNECTION ON" },
            { SimVariable.AlternatorConnectionOn, "ALTERNATOR CONNECTION ON" },
            { SimVariable.CircuitConnectionOn, "CIRCUIT CONNECTION ON" },
            { SimVariable.BusBreakerPulled, "BUS BREAKER PULLED" },
            { SimVariable.BatteryBreakerPulled, "BATTERY BREAKER PULLED" },
            { SimVariable.AlternatorBreakerPulled, "ALTERNATOR BREAKER PULLED" },
            { SimVariable.CircuitBreakerPulled, "CIRCUIT BREAKER PULLED" },
            { SimVariable.CameraState, "CAMERA STATE" },
            { SimVariable.CameraSubstate, "CAMERA SUBSTATE" },
            { SimVariable.SmartCameraActive, "SMART CAMERA ACTIVE" },
            { SimVariable.CameraRequestAction, "CAMERA REQUEST ACTION" },
            { SimVariable.AdfVolume, "ADF VOLUME" },
            { SimVariable.BleedAirApu, "BLEED AIR APU" },
            { SimVariable.BleedAirEngine, "BLEED AIR ENGINE" },
            { SimVariable.ApuBleedToEngine, "APU BLEED TO ENGINE" },
            { SimVariable.ExternalPowerConnectionOn, "EXTERNAL POWER CONNECTION ON" },
            { SimVariable.ExternalPowerBreakerPulled, "EXTERNAL POWER BREAKER PULLED" },
            { SimVariable.ExternalPowerAvailable, "EXTERNAL POWER AVAILABLE" },
            { SimVariable.ExternalPowerOn, "EXTERNAL POWER ON" },
        };
    }
}
