using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SimConnectNet.Mapping
{
    public static partial class MappingUtils
    {
        public static string ConvertUnitOfMeasurementToSimulationString(UnitOfMeasurement uom)
        {
            if (UnitOfMeasurementMappings.TryGetValue(uom, out var mapping))
            {
                return mapping;
            }

            return null;
        }

        public static bool TryConvertSimulationStringToUnitOfMeasurement(string simString, out UnitOfMeasurement measurement)
        {
            var kvps = UnitOfMeasurementMappings.Where(uom => uom.Value == simString)
                .ToList();

            if (kvps.Any())
            {
                measurement = kvps.FirstOrDefault().Key;
                return true;
            }

            measurement = UnitOfMeasurement.Invalid;
            return false;
        }

        private static readonly Dictionary<UnitOfMeasurement, string> UnitOfMeasurementMappings = new Dictionary<UnitOfMeasurement, string>
        {
            { UnitOfMeasurement.Invalid, "NULL" },
            { UnitOfMeasurement.String, "NULL" },
            { UnitOfMeasurement.Structure, "NULL" },
            { UnitOfMeasurement.FrequencyBcd32, "Frequency BCD32" },
            { UnitOfMeasurement.Inhg, "inHg" },
            { UnitOfMeasurement.Ftmin, "ft/min" },
            { UnitOfMeasurement.M, "m" },
            { UnitOfMeasurement.Yard, "yard" },
            { UnitOfMeasurement.MetersPerSecond, "meters per second" },
            { UnitOfMeasurement.SlugsPerCubicFoot, "Slugs per cubic foot" },
            { UnitOfMeasurement.MeterScaler256, "meter scaler 256" },
            { UnitOfMeasurement.Foot, "foot" },
            { UnitOfMeasurement.NauticalMile, "nautical mile" },
            { UnitOfMeasurement.PercentOver100, "percent over 100" },
            { UnitOfMeasurement.Percentage, "percentage" },
            { UnitOfMeasurement.Fahrenheit, "fahrenheit" },
            { UnitOfMeasurement.KilogramPerCubicMeter, "kilogram per cubic meter" },
            { UnitOfMeasurement.PerSecond, "per second" },
            { UnitOfMeasurement.KilogramMeters, "kilogram meters" },
            { UnitOfMeasurement.Metersecond, "meter/second" },
            { UnitOfMeasurement.In2, "in2" },
            { UnitOfMeasurement.In3, "in3" },
            { UnitOfMeasurement.MetersPerSecondScaler256, "meters per second scaler 256" },
            { UnitOfMeasurement.Ft2, "ft2" },
            { UnitOfMeasurement.Ft3, "ft3" },
            { UnitOfMeasurement.Decinmile, "decinmile" },
            { UnitOfMeasurement.Amperes, "amperes" },
            { UnitOfMeasurement.NiceMinutesPerRound, "nice minutes per round" },
            { UnitOfMeasurement.Enum, "Enum" },
            { UnitOfMeasurement.Farenheit, "farenheit" },
            { UnitOfMeasurement.MeterPerSecondScaler256, "meter per second scaler 256" },
            { UnitOfMeasurement.Bco16, "Bco16" },
            { UnitOfMeasurement.SlugsPerCubicFeet, "Slugs per cubic feet" },
            { UnitOfMeasurement.Feet, "feet" },
            { UnitOfMeasurement.Minutes, "minutes" },
            { UnitOfMeasurement.Decibel, "decibel" },
            { UnitOfMeasurement.DegreeLatitude, "degree latitude" },
            { UnitOfMeasurement.MetersPerSecondSquared, "meters per second squared" },
            { UnitOfMeasurement.Halfs, "halfs" },
            { UnitOfMeasurement.Feetsecond, "feet/second" },
            { UnitOfMeasurement.PoundforcePerSquareFoot, "pound-force per square foot" },
            { UnitOfMeasurement.Slugft3, "Slug/ft3" },
            { UnitOfMeasurement.Kilometerhour, "kilometer/hour" },
            { UnitOfMeasurement.HourOver10, "hour over 10" },
            { UnitOfMeasurement.MinutePerRound, "minute per round" },
            { UnitOfMeasurement.Slugs, "slugs" },
            { UnitOfMeasurement.Mhz, "MHz" },
            { UnitOfMeasurement.Cm, "cm" },
            { UnitOfMeasurement.SqCm, "sq cm" },
            { UnitOfMeasurement.Meterssecond, "meters/second" },
            { UnitOfMeasurement.Boolean, "Boolean" },
            { UnitOfMeasurement.Megahertz, "Megahertz" },
            { UnitOfMeasurement.Km2, "km2" },
            { UnitOfMeasurement.Km3, "km3" },
            { UnitOfMeasurement.MillibarScaler16, "millibar scaler 16" },
            { UnitOfMeasurement.MillimeterOfMercury, "millimeter of mercury" },
            { UnitOfMeasurement.Percent, "percent" },
            { UnitOfMeasurement.RadianPerSecond, "radian per second" },
            { UnitOfMeasurement.MetersCubed, "meters cubed" },
            { UnitOfMeasurement.Inches, "inches" },
            { UnitOfMeasurement.PoundsPerHour, "pounds per hour" },
            { UnitOfMeasurement.Footpounds, "foot-pounds" },
            { UnitOfMeasurement.DegreesPerSecondAng16, "degrees per second ang16" },
            { UnitOfMeasurement.Rpms, "rpms" },
            { UnitOfMeasurement.CubicKilometers, "cubic kilometers" },
            { UnitOfMeasurement.RadiansPerSecond, "radians per second" },
            { UnitOfMeasurement.SlugsFeetSquared, "slugs feet squared" },
            { UnitOfMeasurement.NewtonMeters, "newton meters" },
            { UnitOfMeasurement.Bar, "bar" },
            { UnitOfMeasurement.PsfScaler16K, "psf scaler 16k" },
            { UnitOfMeasurement.Part, "part" },
            { UnitOfMeasurement.CuYd, "cu yd" },
            { UnitOfMeasurement.MeterLatitude, "meter latitude" },
            { UnitOfMeasurement.Mile, "mile" },
            { UnitOfMeasurement.MetersPerMinute, "meters per minute" },
            { UnitOfMeasurement.Kelvin, "kelvin" },
            { UnitOfMeasurement.Machs, "machs" },
            { UnitOfMeasurement.Flags, "flags" },
            { UnitOfMeasurement.Seconds, "seconds" },
            { UnitOfMeasurement.PsiScaler16K, "psi scaler 16k" },
            { UnitOfMeasurement.PerMinute, "per minute" },
            { UnitOfMeasurement.Ft, "ft" },
            { UnitOfMeasurement.Ampere, "ampere" },
            { UnitOfMeasurement.Kpa, "kPa" },
            { UnitOfMeasurement.Half, "half" },
            { UnitOfMeasurement.SqFt, "sq ft" },
            { UnitOfMeasurement.Quarts, "quarts" },
            { UnitOfMeasurement.Kph, "kph" },
            { UnitOfMeasurement.Fs7ChargingAmps, "fs7 charging amps" },
            { UnitOfMeasurement.Pound, "pound" },
            { UnitOfMeasurement.Geepounds, "geepounds" },
            { UnitOfMeasurement.Degree, "degree" },
            { UnitOfMeasurement.KilogramsPerCubicMeter, "kilograms per cubic meter" },
            { UnitOfMeasurement.Keyframe, "keyframe" },
            { UnitOfMeasurement.Slug, "slug" },
            { UnitOfMeasurement.SlugPerCubicFoot, "Slug per cubic foot" },
            { UnitOfMeasurement.CubicInches, "cubic inches" },
            { UnitOfMeasurement.Feetminute, "feet/minute" },
            { UnitOfMeasurement.Mm2, "mm2" },
            { UnitOfMeasurement.Mm3, "mm3" },
            { UnitOfMeasurement.Days, "days" },
            { UnitOfMeasurement.SquareInch, "square inch" },
            { UnitOfMeasurement.MillimetersOfWater, "millimeters of water" },
            { UnitOfMeasurement.Hz, "Hz" },
            { UnitOfMeasurement.Years, "years" },
            { UnitOfMeasurement.SlugPerCubicFeet, "Slug per cubic feet" },
            { UnitOfMeasurement.Hertz, "Hertz" },
            { UnitOfMeasurement.Thirds, "thirds" },
            { UnitOfMeasurement.MillimeterOfWater, "millimeter of water" },
            { UnitOfMeasurement.Bel, "bel" },
            { UnitOfMeasurement.In, "in" },
            { UnitOfMeasurement.SqIn, "sq in" },
            { UnitOfMeasurement.Second, "second" },
            { UnitOfMeasurement.Day, "day" },
            { UnitOfMeasurement.Kilometers, "kilometers" },
            { UnitOfMeasurement.DegreesPerSecond, "degrees per second" },
            { UnitOfMeasurement.MillimetersOfMercury, "millimeters of mercury" },
            { UnitOfMeasurement.Pascals, "pascals" },
            { UnitOfMeasurement.DegreesAngl16, "degrees angl16" },
            { UnitOfMeasurement.Mmhg, "mmHg" },
            { UnitOfMeasurement.Ms, "m/s" },
            { UnitOfMeasurement.Knots, "knots" },
            { UnitOfMeasurement.KilogramPerSecond, "kilogram per second" },
            { UnitOfMeasurement.Decibels, "decibels" },
            { UnitOfMeasurement.CubicMiles, "cubic miles" },
            { UnitOfMeasurement.Inhg64Over64K, "inHg 64 over 64k" },
            { UnitOfMeasurement.Mph, "mph" },
            { UnitOfMeasurement.BoostInhg, "boost inHg" },
            { UnitOfMeasurement.CelsiusScaler1256, "celsius scaler 1/256" },
            { UnitOfMeasurement.FootPerSecondSquared, "foot per second squared" },
            { UnitOfMeasurement.Hours, "hours" },
            { UnitOfMeasurement.Kg, "kg" },
            { UnitOfMeasurement.Km, "km" },
            { UnitOfMeasurement.SqKm, "sq km" },
            { UnitOfMeasurement.Decinmiles, "decinmiles" },
            { UnitOfMeasurement.Cmhg, "cmHg" },
            { UnitOfMeasurement.Millibars, "millibars" },
            { UnitOfMeasurement.Times, "times" },
            { UnitOfMeasurement.DegreesAngl32, "degrees angl32" },
            { UnitOfMeasurement.Rankine, "rankine" },
            { UnitOfMeasurement.Number, "number" },
            { UnitOfMeasurement.SquareMiles, "square miles" },
            { UnitOfMeasurement.KilogramForcePerSquareCentimeter, "kilogram force per square centimeter" },
            { UnitOfMeasurement.DegreePerSecond, "degree per second" },
            { UnitOfMeasurement.KnotScaler128, "knot scaler 128" },
            { UnitOfMeasurement.NewtonMeter, "newton meter" },
            { UnitOfMeasurement.Mach, "mach" },
            { UnitOfMeasurement.Scaler, "scaler" },
            { UnitOfMeasurement.Hour, "hour" },
            { UnitOfMeasurement.Mbar, "mbar" },
            { UnitOfMeasurement.SquareMillimeter, "square millimeter" },
            { UnitOfMeasurement.Atmospheres, "atmospheres" },
            { UnitOfMeasurement.KilogramMeter, "kilogram meter" },
            { UnitOfMeasurement.Position, "position" },
            { UnitOfMeasurement.Pounds, "pounds" },
            { UnitOfMeasurement.Miles, "miles" },
            { UnitOfMeasurement.Third, "third" },
            { UnitOfMeasurement.PercentScaler32K, "percent scaler 32k" },
            { UnitOfMeasurement.PercentScaler16K, "percent scaler 16k" },
            { UnitOfMeasurement.SqMm, "sq mm" },
            { UnitOfMeasurement.M2, "m2" },
            { UnitOfMeasurement.M3, "m3" },
            { UnitOfMeasurement.MilesPerHour, "miles per hour" },
            { UnitOfMeasurement.Radians, "radians" },
            { UnitOfMeasurement.Knot, "knot" },
            { UnitOfMeasurement.Centimeters, "centimeters" },
            { UnitOfMeasurement.Volt, "volt" },
            { UnitOfMeasurement.SquareYard, "square yard" },
            { UnitOfMeasurement.Globalpeng1manifold_Pressure, "GLOBALP->eng1.manifold_pressure" },
            { UnitOfMeasurement.Millimeters, "millimeters" },
            { UnitOfMeasurement.SquareFoot, "square foot" },
            { UnitOfMeasurement.Kilograms, "kilograms" },
            { UnitOfMeasurement.CubicYards, "cubic yards" },
            { UnitOfMeasurement.Kilometershour, "kilometers/hour" },
            { UnitOfMeasurement.MetersLatitude, "meters latitude" },
            { UnitOfMeasurement.Amps, "amps" },
            { UnitOfMeasurement.Nm, "Nm" },
            { UnitOfMeasurement.MillibarsScaler16, "millibars scaler 16" },
            { UnitOfMeasurement.GallonPerHour, "gallon per hour" },
            { UnitOfMeasurement.CubicMeter, "cubic meter" },
            { UnitOfMeasurement.FeetPerSecond, "feet per second" },
            { UnitOfMeasurement.Round, "round" },
            { UnitOfMeasurement.KilogramMeterSquared, "kilogram meter squared" },
            { UnitOfMeasurement.CuCm, "cu cm" },
            { UnitOfMeasurement.CubicCentimeters, "cubic centimeters" },
            { UnitOfMeasurement.MetersScaler256, "meters scaler 256" },
            { UnitOfMeasurement.CubicMillimeters, "cubic millimeters" },
            { UnitOfMeasurement.Meters, "meters" },
            { UnitOfMeasurement.Minute, "minute" },
            { UnitOfMeasurement.SquareYards, "square yards" },
            { UnitOfMeasurement.Mbars, "mbars" },
            { UnitOfMeasurement.SquareFeet, "square feet" },
            { UnitOfMeasurement.Geepound, "geepound" },
            { UnitOfMeasurement.KilogramsMeterSquared, "kilograms meter squared" },
            { UnitOfMeasurement.Globalpeng1oil_Prs, "GLOBALP->eng1.oil_prs" },
            { UnitOfMeasurement.Amp, "amp" },
            { UnitOfMeasurement.Kilopascal, "kilopascal" },
            { UnitOfMeasurement.LiterPerHour, "liter per hour" },
            { UnitOfMeasurement.CelsiusFs7Egt, "celsius fs7 egt" },
            { UnitOfMeasurement.FrequencyAdfBcd32, "Frequency ADF BCD32" },
            { UnitOfMeasurement.SquareMeter, "square meter" },
            { UnitOfMeasurement.Decimiles, "decimiles" },
            { UnitOfMeasurement.PoundsScaler256, "pounds scaler 256" },
            { UnitOfMeasurement.Pa, "Pa" },
            { UnitOfMeasurement.Gforce, "GForce" },
            { UnitOfMeasurement.DegreeLongitude, "degree longitude" },
            { UnitOfMeasurement.FeetPerSecondSquared, "feet per second squared" },
            { UnitOfMeasurement.SquareCentimeter, "square centimeter" },
            { UnitOfMeasurement.Yards, "yards" },
            { UnitOfMeasurement.Ftlbs, "ft-lbs" },
            { UnitOfMeasurement.Pph, "pph" },
            { UnitOfMeasurement.Gallons, "gallons" },
            { UnitOfMeasurement.InchesOfMercury, "inches of mercury" },
            { UnitOfMeasurement.More_Than_A_Half, "more_than_a_half" },
            { UnitOfMeasurement.Meter, "meter" },
            { UnitOfMeasurement.NiceMinutePerRound, "nice minute per round" },
            { UnitOfMeasurement.MeterPerSecond, "meter per second" },
            { UnitOfMeasurement.Hectopascal, "hectopascal" },
            { UnitOfMeasurement.CubicInch, "cubic inch" },
            { UnitOfMeasurement.KilogramsPerSecond, "kilograms per second" },
            { UnitOfMeasurement.CubicKilometer, "cubic kilometer" },
            { UnitOfMeasurement.CuFt, "cu ft" },
            { UnitOfMeasurement.SlugFeetSquared, "slug feet squared" },
            { UnitOfMeasurement.SquareCentimeters, "square centimeters" },
            { UnitOfMeasurement.CubicMeters, "cubic meters" },
            { UnitOfMeasurement.SquareMillimeters, "square millimeters" },
            { UnitOfMeasurement.Globalpeng1oil_Tmp, "GLOBALP->eng1.oil_tmp" },
            { UnitOfMeasurement.PoundPerHour, "pound per hour" },
            { UnitOfMeasurement.RevolutionPerMinute, "revolution per minute" },
            { UnitOfMeasurement.MinutesPerRound, "minutes per round" },
            { UnitOfMeasurement.Volts, "volts" },
            { UnitOfMeasurement.SquareMile, "square mile" },
            { UnitOfMeasurement.Decimile, "decimile" },
            { UnitOfMeasurement.Gallon, "gallon" },
            { UnitOfMeasurement.Degrees, "degrees" },
            { UnitOfMeasurement.Cm2, "cm2" },
            { UnitOfMeasurement.Cm3, "cm3" },
            { UnitOfMeasurement.NewtonsPerSquareMeter, "newtons per square meter" },
            { UnitOfMeasurement.CuM, "cu m" },
            { UnitOfMeasurement.CelsiusScaler16K, "celsius scaler 16k" },
            { UnitOfMeasurement.Nmiles, "nmiles" },
            { UnitOfMeasurement.Psf, "psf" },
            { UnitOfMeasurement.SquareInches, "square inches" },
            { UnitOfMeasurement.Psi, "psi" },
            { UnitOfMeasurement.Bool, "Bool" },
            { UnitOfMeasurement.Fs7OilQuantity, "fs7 oil quantity" },
            { UnitOfMeasurement.Atmosphere, "atmosphere" },
            { UnitOfMeasurement.CubicMillimeter, "cubic millimeter" },
            { UnitOfMeasurement.Kilohertz, "Kilohertz" },
            { UnitOfMeasurement.FeetPerMinute, "feet per minute" },
            { UnitOfMeasurement.MeterCubed, "meter cubed" },
            { UnitOfMeasurement.Lbffeet, "lbf-feet" },
            { UnitOfMeasurement.KgfMeters, "kgf meters" },
            { UnitOfMeasurement.DegreePerSecondAng16, "degree per second ang16" },
            { UnitOfMeasurement.CelsiusScaler256, "celsius scaler 256" },
            { UnitOfMeasurement.Rpm, "rpm" },
            { UnitOfMeasurement.NewtonPerSquareMeter, "newton per square meter" },
            { UnitOfMeasurement.CuIn, "cu in" },
            { UnitOfMeasurement.Pascal, "pascal" },
            { UnitOfMeasurement.PerRadian, "per radian" },
            { UnitOfMeasurement.PoundalFeet, "poundal feet" },
            { UnitOfMeasurement.Numbers, "numbers" },
            { UnitOfMeasurement.MeterCubedPerSecond, "meter cubed per second" },
            { UnitOfMeasurement.PerHour, "per hour" },
            { UnitOfMeasurement.Psi4Over16K, "psi 4 over 16k" },
            { UnitOfMeasurement.FootPounds, "foot pounds" },
            { UnitOfMeasurement.MetersCubedPerSecond, "meters cubed per second" },
            { UnitOfMeasurement.PsiFs7OilPressure, "psi fs7 oil pressure" },
            { UnitOfMeasurement.CelsiusFs7OilTemp, "celsius fs7 oil temp" },
            { UnitOfMeasurement.Atm, "atm" },
            { UnitOfMeasurement.KilometersPerHour, "kilometers per hour" },
            { UnitOfMeasurement.BoostCmhg, "boost cmHg" },
            { UnitOfMeasurement.Yd2, "yd2" },
            { UnitOfMeasurement.Position128, "position 128" },
            { UnitOfMeasurement.Yd3, "yd3" },
            { UnitOfMeasurement.CuKm, "cu km" },
            { UnitOfMeasurement.Year, "year" },
            { UnitOfMeasurement.GallonsPerHour, "gallons per hour" },
            { UnitOfMeasurement.GForce, "G Force" },
            { UnitOfMeasurement.CubicYard, "cubic yard" },
            { UnitOfMeasurement.Kilogram, "kilogram" },
            { UnitOfMeasurement.MeterPerMinute, "meter per minute" },
            { UnitOfMeasurement.Rounds, "rounds" },
            { UnitOfMeasurement.CubicFoot, "cubic foot" },
            { UnitOfMeasurement.FootPound, "foot pound" },
            { UnitOfMeasurement.Globalpdelta_Heading_Rate, "GLOBALP->delta_heading_rate" },
            { UnitOfMeasurement.BoostPsi, "boost psi" },
            { UnitOfMeasurement.DegreeAngl16, "degree angl16" },
            { UnitOfMeasurement.CubicCentimeter, "cubic centimeter" },
            { UnitOfMeasurement.PoundScaler256, "pound scaler 256" },
            { UnitOfMeasurement.CubicFeet, "cubic feet" },
            { UnitOfMeasurement.NauticalMiles, "nautical miles" },
            { UnitOfMeasurement.Footpound, "foot-pound" },
            { UnitOfMeasurement.Quart, "quart" },
            { UnitOfMeasurement.HoursOver10, "hours over 10" },
            { UnitOfMeasurement.Grads, "grads" },
            { UnitOfMeasurement.CuMm, "cu mm" },
            { UnitOfMeasurement.Millimeter, "millimeter" },
            { UnitOfMeasurement.Hectopascals, "hectopascals" },
            { UnitOfMeasurement.DegreesLatitude, "degrees latitude" },
            { UnitOfMeasurement.GForce624Scaled, "G Force 624 scaled" },
            { UnitOfMeasurement.Liter, "liter" },
            { UnitOfMeasurement.SqYd, "sq yd" },
            { UnitOfMeasurement.KnotsScaler128, "knots scaler 128" },
            { UnitOfMeasurement.FtLbPerSecond, "ft lb per second" },
            { UnitOfMeasurement.DegreeAngl32, "degree angl32" },
            { UnitOfMeasurement.Liters, "liters" },
            { UnitOfMeasurement.Grad, "grad" },
            { UnitOfMeasurement.Lbs, "lbs" },
            { UnitOfMeasurement.Inch, "inch" },
            { UnitOfMeasurement.Position32K, "position 32k" },
            { UnitOfMeasurement.Position16K, "position 16k" },
            { UnitOfMeasurement.Bars, "bars" },
            { UnitOfMeasurement.DegreesLongitude, "degrees longitude" },
            { UnitOfMeasurement.MilePerHour, "mile per hour" },
            { UnitOfMeasurement.MeterPerSecondSquared, "meter per second squared" },
            { UnitOfMeasurement.Globalpvertical_Speed, "GLOBALP->vertical_speed" },
            { UnitOfMeasurement.LitersPerHour, "liters per hour" },
            { UnitOfMeasurement.RevolutionsPerMinute, "revolutions per minute" },
            { UnitOfMeasurement.Keyframes, "keyframes" },
            { UnitOfMeasurement.CentimeterOfMercury, "centimeter of mercury" },
            { UnitOfMeasurement.SqM, "sq m" },
            { UnitOfMeasurement.PoundforcePerSquareInch, "pound-force per square inch" },
            { UnitOfMeasurement.Watt, "Watt" },
            { UnitOfMeasurement.Bels, "bels" },
            { UnitOfMeasurement.Angl16, "angl16" },
            { UnitOfMeasurement.Kgfsqcm, "KgFSqCm" },
            { UnitOfMeasurement.Mask, "mask" },
            { UnitOfMeasurement.Rpm1Over16K, "rpm 1 over 16k" },
            { UnitOfMeasurement.Kilometer, "kilometer" },
            { UnitOfMeasurement.SquareKilometers, "square kilometers" },
            { UnitOfMeasurement.Centimeter, "centimeter" },
            { UnitOfMeasurement.CubicMile, "cubic mile" },
            { UnitOfMeasurement.Watts, "Watts" },
            { UnitOfMeasurement.Celsius, "celsius" },
            { UnitOfMeasurement.Ratio, "ratio" },
            { UnitOfMeasurement.CentimetersOfMercury, "centimeters of mercury" },
            { UnitOfMeasurement.FrequencyBcd16, "Frequency BCD16" },
            { UnitOfMeasurement.Radian, "radian" },
            { UnitOfMeasurement.PerDegree, "per degree" },
            { UnitOfMeasurement.Nmile, "nmile" },
            { UnitOfMeasurement.Gph, "gph" },
            { UnitOfMeasurement.SquareMeters, "square meters" },
            { UnitOfMeasurement.Angl32, "angl32" },
            { UnitOfMeasurement.Millibar, "millibar" },
            { UnitOfMeasurement.Khz, "KHz" },
            { UnitOfMeasurement.KilometerPerHour, "kilometer per hour" },
            { UnitOfMeasurement.Mach3D2Over64K, "mach 3d2 over 64k" },
            { UnitOfMeasurement.KgfMeter, "kgf meter" },
            { UnitOfMeasurement.PercentScaler2Pow23, "percent scaler 2pow23" },
            { UnitOfMeasurement.SquareKilometer, "square kilometer" },
            { UnitOfMeasurement.InchOfMercury, "inch of mercury" },
        };
    }
}
